# $OpenBSD$

COMMENT=	Tor Browser Bundler meta-package

PKGNAME=	tbb-4.1.5

RUN_DEPENDS=	www/tbb/tor-browser \
		www/tbb/torbutton \
		www/tbb/tor-launcher \
		www/tbb/tbb-noscript \
		www/tbb/https-everywhere

.include <bsd.port.mk>
