# $OpenBSD$

COMMENT=	Tor Browser Bundle meta-package

MAINTAINER=	Sean Levy <attila@stalphonsos.com>

PKGNAME=	tbb-6.0.5

RUN_DEPENDS=	www/tbb/tor-browser \
		www/tbb/torbutton \
		www/tbb/tor-launcher \
		www/tbb/noscript \
		www/tbb/https-everywhere

.include <bsd.port.mk>
