# $OpenBSD$

COMMENT=	Tor Browser Bundle meta-package

MAINTAINER=	Sean Levy <attila@stalphonsos.com>

PKGNAME=	tbb-4.5.2

RUN_DEPENDS=	www/tbb/tor-browser-4.5.2 \
		www/tbb/torbutton-1.9.2.6 \
		www/tbb/tor-launcher-0.2.7.5 \
		www/tbb/noscript-2.6.9.26 \
		www/tbb/https-everywhere-5.0.5

.include <bsd.port.mk>
