# -*- mode:org; indent-tabs-mode:nil; tab-width:2 -*-

This is an ORG-MODE file.  Lines that begin with stars (*) are headings.
Hit TAB on a line that begins with a star to expand it and collapse it.

* tor-browser
** 2015-02-20
The only patch from www/firefox-esr that conflicts with the patches
I generated for tor-browser is patch-browser_installer_Makefile_in.
The others are all orthongonal, it seems

*** List of 600 original patches from diffsplit.pl
patch-Makefile_in
patch-_gitignore
patch-_mozconfig
patch-_mozconfig-asan
patch-_mozconfig-mac
patch-_mozconfig-mingw
patch-accessible_src_jsat_EventManager_jsm
patch-browser_app_Makefile_in
patch-browser_app_blocklist_xml
patch-browser_app_profile_000-tor-browser_js
patch-browser_app_profile_firefox_js
patch-browser_base_content_aboutDialog_js
patch-browser_base_content_browser-plugins_js
patch-browser_base_content_browser_js
patch-browser_base_content_browser_xul
patch-browser_base_content_newtab_newTab_css
patch-browser_base_content_test_general_browser_aboutHome_js
patch-browser_base_content_test_general_browser_ini
patch-browser_base_content_test_general_browser_keywordSearch_js
patch-browser_branding_official_background_png
patch-browser_branding_official_configure_sh
patch-browser_branding_official_default16_png
patch-browser_branding_official_default22_png
patch-browser_branding_official_default24_png
patch-browser_branding_official_default256_png
patch-browser_branding_official_default32_png
patch-browser_branding_official_default48_png
patch-browser_branding_official_disk_icns
patch-browser_branding_official_document_icns
patch-browser_branding_official_document_ico
patch-browser_branding_official_firefox_icns
patch-browser_branding_official_firefox_ico
patch-browser_branding_official_locales_en-US_brand_dtd
patch-browser_branding_official_locales_en-US_brand_properties
patch-browser_branding_official_mozicon128_png
patch-browser_branding_official_pref_firefox-branding_js
patch-browser_branding_official_wizHeaderRTL_bmp
patch-browser_branding_official_wizHeader_bmp
patch-browser_branding_official_wizWatermark_bmp
patch-browser_components_search_test_browser_426329_js
patch-browser_components_search_test_browser_google_behavior_js
patch-browser_components_search_test_browser_google_js
patch-browser_components_search_test_head_js
patch-browser_components_sessionstore_src_SessionStorage_jsm
patch-browser_components_tabview_test_browser_tabview_bug598600_js
patch-browser_components_tabview_test_browser_tabview_bug651311_js
patch-browser_components_tabview_test_browser_tabview_bug712203_js
patch-browser_components_tabview_test_head_js
patch-browser_config_mozconfigs_linux32_debug
patch-browser_config_mozconfigs_linux64_debug
patch-browser_config_mozconfigs_linux64_debug-nonunified
patch-browser_config_mozconfigs_linux64_debug-static-analysis-clang
patch-browser_config_mozconfigs_linux64_nightly-nonunified
patch-browser_config_mozconfigs_macosx-universal_nightly-nonunified
patch-browser_config_mozconfigs_macosx64_debug-nonunified
patch-browser_config_mozconfigs_win32_beta
patch-browser_config_mozconfigs_win32_debug
patch-browser_config_mozconfigs_win32_debug-nonunified
patch-browser_config_mozconfigs_win32_nightly
patch-browser_config_mozconfigs_win32_nightly-nonunified
patch-browser_config_mozconfigs_win32_release
patch-browser_config_mozconfigs_win64_beta
patch-browser_config_mozconfigs_win64_debug
patch-browser_config_mozconfigs_win64_nightly
patch-browser_config_mozconfigs_win64_release
patch-browser_config_version_txt
patch-browser_confvars_sh
patch-browser_devtools_styleeditor_test_head_js
patch-browser_installer_Makefile_in
patch-browser_installer_package-manifest_in
patch-browser_installer_removed-files_in
patch-browser_installer_windows_nsis_shared_nsh
patch-browser_locales_en-US_chrome_browser_browser_properties
patch-browser_locales_en-US_searchplugins_bing_xml
patch-browser_locales_en-US_searchplugins_disconnect_xml
patch-browser_locales_en-US_searchplugins_duckduckgo_xml
patch-browser_locales_en-US_searchplugins_google_xml
patch-browser_locales_en-US_searchplugins_list_txt
patch-browser_locales_en-US_searchplugins_startpage_xml
patch-browser_locales_en-US_searchplugins_youtube_xml
patch-browser_themes_linux_browser_css
patch-browser_themes_linux_canvas-popup_svg
patch-browser_themes_linux_jar_mn
patch-browser_themes_osx_browser_css
patch-browser_themes_osx_canvas-popup_svg
patch-browser_themes_osx_jar_mn
patch-browser_themes_windows_browser_css
patch-browser_themes_windows_canvas-popup_svg
patch-browser_themes_windows_jar_mn
patch-build_automation_py_in
patch-build_automationutils_py
patch-build_gen_mach_buildprops_py
patch-build_mach_bootstrap_py
patch-build_macosx_mozconfig_common
patch-build_moz-automation_mk
patch-build_mozconfig_automation
patch-build_mozconfig_common
patch-build_mozconfig_win-common
patch-build_unix_mozconfig_asan
patch-build_unix_mozconfig_linux
patch-caps_src_nsScriptSecurityManager_cpp
patch-caps_tests_mochitest_test_bug995943_xul
patch-client_mk
patch-config_createprecomplete_py
patch-config_milestone_txt
patch-config_version_mk
patch-configure_in
patch-content_base_public_DirectionalityUtils_h
patch-content_base_src_DirectionalityUtils_cpp
patch-content_base_src_ThirdPartyUtil_cpp
patch-content_base_src_ThirdPartyUtil_h
patch-content_base_src_nsContentUtils_cpp
patch-content_base_src_nsDocument_cpp
patch-content_base_src_nsGenericDOMDataNode_cpp
patch-content_base_src_nsScriptLoader_cpp
patch-content_base_src_nsXMLHttpRequest_h
patch-content_base_test_echo_sjs
patch-content_base_test_mochitest_ini
patch-content_base_test_test_xhr_send_html
patch-content_canvas_src_CanvasGradient_h
patch-content_canvas_src_CanvasRenderingContext2D_cpp
patch-content_canvas_src_CanvasRenderingContext2D_h
patch-content_canvas_src_CanvasUtils_cpp
patch-content_canvas_src_CanvasUtils_h
patch-content_canvas_src_ImageEncoder_cpp
patch-content_canvas_src_ImageEncoder_h
patch-content_canvas_test_webgl-conformance_skipped_tests_android_txt
patch-content_canvas_test_webgl-conformance_skipped_tests_android_x86_txt
patch-content_canvas_test_webgl-conformance_skipped_tests_linux_mesa_txt
patch-content_canvas_test_webgl-conformance_skipped_tests_linux_txt
patch-content_html_content_public_HTMLCanvasElement_h
patch-content_html_content_src_HTMLCanvasElement_cpp
patch-content_html_content_test_file_iframe_sandbox_e_if6_html
patch-content_html_content_test_file_iframe_sandbox_form_pass_html
patch-content_media_AudioEventTimeline_h
patch-content_media_MediaCache_cpp
patch-content_media_test_test_load_candidates_html
patch-content_media_webaudio_OscillatorNode_cpp
patch-content_media_webaudio_test_test_periodicWave_html
patch-content_media_webm_WebMReader_cpp
patch-content_svg_content_src_DOMSVGLengthList_cpp
patch-content_svg_content_src_DOMSVGLength_cpp
patch-content_svg_content_src_DOMSVGLength_h
patch-content_svg_content_src_DOMSVGPointList_cpp
patch-content_svg_content_src_DOMSVGPoint_h
patch-content_svg_content_src_SVGSVGElement_cpp
patch-content_svg_content_src_SVGSVGElement_h
patch-content_svg_content_src_nsISVGPoint_h
patch-content_svg_content_test_test_SVGLengthList_xhtml
patch-content_svg_content_test_test_SVGPointList_xhtml
patch-docshell_base_nsDocShell_cpp
patch-docshell_test_test_bug529119-2_html
patch-dom_alarm_AlarmsManager_js
patch-dom_alarm_test_file_empty_html
patch-dom_alarm_test_mochitest_ini
patch-dom_alarm_test_test_bug1015540_html
patch-dom_alarm_test_test_bug1037079_html
patch-dom_base_Navigator_cpp
patch-dom_base_Navigator_h
patch-dom_base_WindowNamedPropertiesHandler_cpp
patch-dom_base_WindowNamedPropertiesHandler_h
patch-dom_base_nsDOMClassInfo_cpp
patch-dom_base_nsGlobalWindow_cpp
patch-dom_base_nsGlobalWindow_h
patch-dom_base_nsPerformance_cpp
patch-dom_base_nsScreen_cpp
patch-dom_base_nsScreen_h
patch-dom_bindings_Bindings_conf
patch-dom_bindings_Codegen_py
patch-dom_bindings_DOMJSProxyHandler_cpp
patch-dom_bindings_DOMJSProxyHandler_h
patch-dom_bindings_test_mochitest_ini
patch-dom_bindings_test_test_setWithNamedGetterNoNamedSetter_html
patch-dom_browser-element_BrowserElementChildPreload_js
patch-dom_events_Event_cpp
patch-dom_events_test_test_bug432698_html
patch-dom_interfaces_storage_nsIDOMStorageManager_idl
patch-dom_media_MediaManager_cpp
patch-dom_media_MediaManager_h
patch-dom_plugins_base_moz_build
patch-dom_plugins_base_nsPluginHost_cpp
patch-dom_plugins_base_nsPluginHost_h
patch-dom_plugins_ipc_PluginModuleChild_cpp
patch-dom_plugins_ipc_PluginModuleParent_cpp
patch-dom_plugins_ipc_PluginProcessChild_cpp
patch-dom_plugins_test_mochitest_dialog_watcher_js
patch-dom_plugins_test_mochitest_test_hangui_xul
patch-dom_src_storage_DOMStorageCache_cpp
patch-dom_src_storage_DOMStorageCache_h
patch-dom_src_storage_DOMStorageManager_cpp
patch-dom_src_storage_DOMStorageManager_h
patch-dom_tests_mochitest_beacon_beacon-originheader-handler_sjs
patch-dom_tests_mochitest_beacon_mochitest_ini
patch-dom_tests_mochitest_beacon_test_beaconOriginHeader_html
patch-dom_tests_mochitest_localstorage_firstPartyInner_html
patch-dom_tests_mochitest_localstorage_firstParty_html
patch-dom_tests_mochitest_localstorage_mochitest_ini
patch-dom_tests_mochitest_localstorage_test_localStorageByFirstParty_html
patch-dom_workers_Navigator_cpp
patch-dom_workers_Navigator_h
patch-dom_workers_RuntimeService_cpp
patch-dom_workers_RuntimeService_h
patch-dom_workers_WorkerScope_cpp
patch-dom_workers_XMLHttpRequest_cpp
patch-dom_workers_test_bug1060621_worker_js
patch-dom_workers_test_bug1062920_worker_js
patch-dom_workers_test_chrome_ini
patch-dom_workers_test_mochitest_ini
patch-dom_workers_test_test_bug1060621_html
patch-dom_workers_test_test_bug1062920_html
patch-dom_workers_test_test_bug1062920_xul
patch-dom_workers_test_test_multi_sharedWorker_lifetimes_html
patch-embedding_browser_webBrowser_nsContextMenuInfo_cpp
patch-embedding_components_windowwatcher_src_nsWindowWatcher_cpp
patch-extensions_auth_nsHttpNegotiateAuth_cpp
patch-extensions_cookie_nsCookiePermission_cpp
patch-extensions_cookie_nsPermissionManager_cpp
patch-extensions_cookie_test_unit_test_cookies_read_js
patch-gfx_2d_Blur_cpp
patch-gfx_2d_Blur_h
patch-gfx_2d_DrawTargetCairo_cpp
patch-gfx_layers_basic_BasicLayerManager_cpp
patch-gfx_thebes_gfxBlur_cpp
patch-gfx_thebes_gfxFont_cpp
patch-gfx_thebes_gfxPangoFonts_cpp
patch-gfx_thebes_gfxUserFontSet_cpp
patch-gfx_thebes_gfxUserFontSet_h
patch-image_public_imgILoader_idl
patch-image_src_ImageURL_h
patch-image_src_imgFrame_cpp
patch-image_src_imgLoader_cpp
patch-image_src_imgLoader_h
patch-image_src_imgRequest_cpp
patch-image_src_imgRequest_h
patch-image_test_mochitest_test_animSVGImage2_html
patch-ipc_glue_MessageChannel_cpp
patch-ipc_glue_MessageChannel_h
patch-ipc_glue_WindowsMessageLoop_cpp
patch-ipc_glue_WindowsMessageLoop_h
patch-ipc_glue_moz_build
patch-js_public_Class_h
patch-js_src_assembler_assembler_MacroAssemblerX86Common_cpp
patch-js_src_builtin_Intl_cpp
patch-js_src_configure_in
patch-js_src_jit-test_lib_asm_js
patch-js_src_jit-test_tests_asm_js_testBullet_js
patch-js_src_jit-test_tests_asm_js_testCaching_js
patch-js_src_jit-test_tests_asm_js_testHeapAccess_js
patch-js_src_jit-test_tests_asm_js_testSource_js
patch-js_src_jit-test_tests_asm_js_testStackWalking_js
patch-js_src_jit-test_tests_debug_optimized-out-01_js
patch-js_src_jit_CompileInfo_h
patch-js_src_jit_IonAnalysis_cpp
patch-js_src_jit_IonBuilder_cpp
patch-js_src_jit_IonMacroAssembler_cpp
patch-js_src_jit_Ion_cpp
patch-js_src_jit_JitCompartment_h
patch-js_src_jit_LIR_h
patch-js_src_jit_MIR_cpp
patch-js_src_jit_VMFunctions_h
patch-js_src_jit_arm_MacroAssembler-arm_cpp
patch-js_src_jit_arm_MacroAssembler-arm_h
patch-js_src_jit_arm_Trampoline-arm_cpp
patch-js_src_jit_mips_MacroAssembler-mips_cpp
patch-js_src_jit_mips_MacroAssembler-mips_h
patch-js_src_jit_mips_Trampoline-mips_cpp
patch-js_src_jit_shared_MacroAssembler-x86-shared_h
patch-js_src_jit_x64_MacroAssembler-x64_cpp
patch-js_src_jit_x64_MacroAssembler-x64_h
patch-js_src_jit_x64_Trampoline-x64_cpp
patch-js_src_jit_x86_MacroAssembler-x86_cpp
patch-js_src_jit_x86_MacroAssembler-x86_h
patch-js_src_jit_x86_Trampoline-x86_cpp
patch-js_src_js-config_h_in
patch-js_src_jsapi-tests_moz_build
patch-js_src_jsapi-tests_testDefineGetterSetterNonEnumerable_cpp
patch-js_src_jsapi-tests_testSetPropertyIgnoringNamedGetter_cpp
patch-js_src_jsapi_cpp
patch-js_src_jsapi_h
patch-js_src_jsfriendapi_h
patch-js_src_jsobj_cpp
patch-js_src_jsobjinlines_h
patch-js_src_jsproxy_cpp
patch-js_src_jsworkers_cpp
patch-js_src_shell_js_cpp
patch-js_src_vm_Shape_cpp
patch-js_src_vm_Shape_h
patch-js_xpconnect_src_XPCWrappedNativeJSOps_cpp
patch-js_xpconnect_tests_mochitest_mochitest_ini
patch-js_xpconnect_tests_mochitest_test_bug790732_html
patch-js_xpconnect_wrappers_XrayWrapper_cpp
patch-layout_base_RestyleManager_cpp
patch-layout_base_nsIPresShell_h
patch-layout_base_nsLayoutUtils_cpp
patch-layout_base_nsLayoutUtils_h
patch-layout_base_nsPresContext_cpp
patch-layout_base_nsPresContext_h
patch-layout_base_nsPresShell_cpp
patch-layout_base_tests_bug1007065-1-ref_html
patch-layout_base_tests_bug1007065-1_html
patch-layout_generic_nsFrame_cpp
patch-layout_generic_nsImageFrame_cpp
patch-layout_generic_test_mochitest_ini
patch-layout_generic_test_test_bug470212_html
patch-layout_style_nsCSSParser_cpp
patch-layout_style_nsComputedDOMStyle_cpp
patch-layout_style_nsFontFaceLoader_cpp
patch-layout_style_nsFontFaceLoader_h
patch-layout_style_nsMediaFeatures_cpp
patch-layout_style_nsRuleNode_cpp
patch-mach
patch-media_libcubeb_src_cubeb_wasapi_cpp
patch-media_libcubeb_tests_test_sanity_cpp
patch-media_libnestegg_include_nestegg-stdint_h
patch-media_libnestegg_src_nestegg_c
patch-media_libspeex_resampler_src_resample_c
patch-media_libvpx_vp9_decoder_vp9_decodframe_c
patch-media_libyuv_source_cpu_id_cc
patch-media_mtransport_test_moz_build
patch-media_mtransport_third_party_nICEr_src_stun_stun_codec_c
patch-media_mtransport_third_party_nrappkit_src_util_byteorder_c
patch-media_mtransport_third_party_nrappkit_src_util_byteorder_h
patch-media_webrtc_signaling_src_peerconnection_PeerConnectionImpl_cpp
patch-media_webrtc_signaling_src_peerconnection_PeerConnectionImpl_h
patch-media_webrtc_signaling_src_peerconnection_PeerConnectionMedia_cpp
patch-media_webrtc_signaling_src_peerconnection_PeerConnectionMedia_h
patch-media_webrtc_signaling_src_sipcc_core_gsm_h_fsm_h
patch-media_webrtc_signaling_src_sipcc_core_sdp_sdp_attr_c
patch-media_webrtc_signaling_src_sipcc_core_sdp_sdp_main_c
patch-media_webrtc_signaling_test_sdp_unittests_cpp
patch-memory_mozalloc_VolatileBuffer_h
patch-mfbt_Char16_h
patch-mobile_android_base_Makefile_in
patch-mobile_android_base_tests_BaseTest_java
patch-mobile_android_base_tests_testSearchSuggestions_java
patch-mobile_android_components_HelperAppDialog_js
patch-mobile_android_config_armv6_play_store_version_code_txt
patch-mobile_android_config_mozconfigs_common
patch-mobile_android_confvars_sh
patch-mobile_locales_en-US_searchplugins_google_xml
patch-modules_libjar_nsJARChannel_cpp
patch-modules_libmar_moz_build
patch-modules_libmar_sign_mar_sign_c
patch-modules_libmar_sign_moz_build
patch-modules_libmar_src_mar_cmdline_h
patch-modules_libmar_src_mar_h
patch-modules_libmar_src_mar_private_h
patch-modules_libmar_tool_Makefile_in
patch-modules_libmar_tool_mar_c
patch-modules_libmar_tool_moz_build
patch-modules_libmar_verify_cryptox_c
patch-modules_libmar_verify_cryptox_h
patch-modules_libmar_verify_mar_verify_c
patch-modules_libmar_verify_moz_build
patch-modules_libpref_src_init_all_js
patch-mozglue_build_WindowsDllBlocklist_cpp
patch-netwerk_base_public_mozIThirdPartyUtil_idl
patch-netwerk_base_public_nsICachingChannel_idl
patch-netwerk_base_public_nsIProtocolProxyCallback_idl
patch-netwerk_base_public_nsIProtocolProxyFilter_idl
patch-netwerk_base_public_nsIProtocolProxyService2_idl
patch-netwerk_base_public_nsIProtocolProxyService_idl
patch-netwerk_base_public_nsIProxyInfo_idl
patch-netwerk_base_public_security-prefs_js
patch-netwerk_base_src_nsIOService_cpp
patch-netwerk_base_src_nsPACMan_cpp
patch-netwerk_base_src_nsPACMan_h
patch-netwerk_base_src_nsProtocolProxyService_cpp
patch-netwerk_base_src_nsProtocolProxyService_h
patch-netwerk_base_src_nsProxyInfo_cpp
patch-netwerk_base_src_nsProxyInfo_h
patch-netwerk_base_src_nsSocketTransport2_cpp
patch-netwerk_base_src_nsSocketTransport2_h
patch-netwerk_base_src_nsStandardURL_cpp
patch-netwerk_cache_nsCacheService_cpp
patch-netwerk_dns_effective_tld_names_dat
patch-netwerk_dns_nsDNSService2_cpp
patch-netwerk_dns_nsDNSService2_h
patch-netwerk_protocol_ftp_nsFtpConnectionThread_cpp
patch-netwerk_protocol_http_HttpBaseChannel_cpp
patch-netwerk_protocol_http_HttpBaseChannel_h
patch-netwerk_protocol_http_nsHttpChannel_cpp
patch-netwerk_protocol_http_nsHttpChannel_h
patch-netwerk_protocol_http_nsHttpConnectionInfo_cpp
patch-netwerk_protocol_http_nsHttpConnectionInfo_h
patch-netwerk_protocol_http_nsHttpConnectionMgr_cpp
patch-netwerk_protocol_http_nsHttpConnectionMgr_h
patch-netwerk_protocol_http_nsHttpConnection_cpp
patch-netwerk_protocol_http_nsHttpHandler_cpp
patch-netwerk_protocol_http_nsHttpHandler_h
patch-netwerk_protocol_http_nsHttpNTLMAuth_cpp
patch-netwerk_protocol_http_nsHttpPipeline_cpp
patch-netwerk_protocol_http_nsHttpPipeline_h
patch-netwerk_protocol_http_nsHttpTransaction_cpp
patch-netwerk_protocol_http_nsHttpTransaction_h
patch-netwerk_protocol_http_nsIHttpChannel_idl
patch-netwerk_protocol_viewsource_nsViewSourceChannel_cpp
patch-netwerk_protocol_websocket_WebSocketChannel_cpp
patch-netwerk_sctp_datachannel_DataChannelProtocol_h
patch-netwerk_sctp_datachannel_DataChannel_cpp
patch-netwerk_sctp_src_moz_build
patch-netwerk_sctp_src_netinet_sctp_callout_c
patch-netwerk_sctp_src_netinet_sctp_callout_h
patch-netwerk_sctp_src_netinet_sctp_usrreq_c
patch-netwerk_sctp_src_user_sctp_timer_iterate_c
patch-netwerk_socket_nsISocketProvider_idl
patch-netwerk_socket_nsSOCKSIOLayer_cpp
patch-netwerk_socket_nsSOCKSIOLayer_h
patch-netwerk_socket_nsSOCKSSocketProvider_cpp
patch-netwerk_socket_nsUDPSocketProvider_cpp
patch-netwerk_test_browser_browser_cacheFirstParty_js
patch-netwerk_test_browser_browser_ini
patch-netwerk_test_browser_firstPartyGrandParent_html
patch-netwerk_test_browser_firstPartyParent_html
patch-netwerk_test_browser_thirdPartyChild_audio_ogg
patch-netwerk_test_browser_thirdPartyChild_embed_png
patch-netwerk_test_browser_thirdPartyChild_iframe_html
patch-netwerk_test_browser_thirdPartyChild_img_png
patch-netwerk_test_browser_thirdPartyChild_link_css
patch-netwerk_test_browser_thirdPartyChild_object_png
patch-netwerk_test_browser_thirdPartyChild_script_js
patch-netwerk_test_browser_thirdPartyChild_track_vtt
patch-netwerk_test_browser_thirdPartyChild_video_ogv
patch-netwerk_test_browser_thirdPartyChild_xhr_html
patch-netwerk_test_unit_test_auth_proxy_js
patch-parser_html_nsHtml5Parser_cpp
patch-parser_html_nsHtml5Parser_h
patch-parser_html_nsHtml5StreamParser_cpp
patch-parser_html_nsHtml5StreamParser_h
patch-parser_html_nsHtml5TreeBuilderCppSupplement_h
patch-parser_html_nsHtml5TreeBuilderHSupplement_h
patch-parser_html_nsHtml5TreeOpExecutor_cpp
patch-parser_html_nsHtml5TreeOpExecutor_h
patch-parser_html_nsHtml5TreeOperation_cpp
patch-parser_html_nsHtml5TreeOperation_h
patch-python_mach_mach_main_py
patch-python_mach_mach_test_test_conditions_py
patch-python_mozbuild_mozbuild_base_py
patch-python_mozbuild_mozbuild_controller_building_py
patch-python_mozbuild_mozbuild_mach_commands_py
patch-python_mozbuild_mozbuild_test_test_base_py
patch-security_apps_AppTrustDomain_h
patch-security_build_Makefile_in
patch-security_build_moz_build
patch-security_certverifier_CertVerifier_cpp
patch-security_certverifier_CertVerifier_h
patch-security_certverifier_NSSCertDBTrustDomain_cpp
patch-security_certverifier_NSSCertDBTrustDomain_h
patch-security_certverifier_moz_build
patch-security_manager_boot_src_PublicKeyPinningService_cpp
patch-security_manager_boot_src_PublicKeyPinningService_cpp_rej
patch-security_manager_boot_src_PublicKeyPinningService_h
patch-security_manager_boot_src_StaticHPKPins_h
patch-security_manager_boot_src_moz_build
patch-security_manager_boot_src_nsSTSPreloadList_errors
patch-security_manager_boot_src_nsSTSPreloadList_inc
patch-security_manager_ssl_src_NSSErrorsService_cpp
patch-security_manager_ssl_src_SSLServerCertVerification_cpp
patch-security_manager_ssl_src_SharedCertVerifier_h
patch-security_manager_ssl_src_nsCMS_cpp
patch-security_manager_ssl_src_nsNSSCertificateDB_cpp
patch-security_manager_ssl_src_nsNSSCertificate_cpp
patch-security_manager_ssl_src_nsNSSComponent_cpp
patch-security_manager_ssl_src_nsNSSIOLayer_cpp
patch-security_manager_ssl_src_nsNSSIOLayer_h
patch-security_manager_ssl_src_nsSSLSocketProvider_cpp
patch-security_manager_ssl_src_nsTLSSocketProvider_cpp
patch-security_manager_ssl_src_nsUsageArrayHelper_cpp
patch-security_manager_ssl_tests_unit_head_psm_js
patch-security_manager_ssl_tests_unit_test_cert_overrides_js
patch-security_manager_ssl_tests_unit_test_pinning_js
patch-security_manager_ssl_tests_unit_tlsserver_cert8_db
patch-security_manager_ssl_tests_unit_tlsserver_cmd_BadCertServer_cpp
patch-security_manager_ssl_tests_unit_tlsserver_default-ee_der
patch-security_manager_ssl_tests_unit_tlsserver_generate_certs_sh
patch-security_manager_ssl_tests_unit_tlsserver_key3_db
patch-security_manager_ssl_tests_unit_tlsserver_other-test-ca_der
patch-security_manager_ssl_tests_unit_tlsserver_secmod_db
patch-security_manager_ssl_tests_unit_tlsserver_test-ca_der
patch-security_manager_ssl_tests_unit_xpcshell_ini
patch-security_manager_tools_PreloadedHPKPins_json
patch-security_manager_tools_genHPKPStaticPins_js
patch-security_nss_TAG-INFO
patch-security_nss_coreconf_coreconf_dep
patch-security_nss_lib_certhigh_ocsp_c
patch-security_nss_lib_cryptohi_secvfy_c
patch-security_nss_lib_freebl_ec_c
patch-security_nss_lib_freebl_rsa_c
patch-security_nss_lib_libpkix_pkix_pl_nss_module_pkix_pl_socket_c
patch-security_nss_lib_nss_nss_h
patch-security_nss_lib_softoken_pkcs11_c
patch-security_nss_lib_softoken_pkcs11c_c
patch-security_nss_lib_softoken_softkver_h
patch-security_nss_lib_ssl_SSLerrs_h
patch-security_nss_lib_ssl_ssl3con_c
patch-security_nss_lib_ssl_ssl3prot_h
patch-security_nss_lib_ssl_ssl_h
patch-security_nss_lib_ssl_sslerr_h
patch-security_nss_lib_ssl_sslimpl_h
patch-security_nss_lib_ssl_sslproto_h
patch-security_nss_lib_ssl_sslsock_c
patch-security_nss_lib_util_manifest_mn
patch-security_nss_lib_util_nssutil_def
patch-security_nss_lib_util_nssutil_h
patch-security_nss_lib_util_pkcs1sig_c
patch-security_nss_lib_util_pkcs1sig_h
patch-security_nss_tests_chains_chains_sh
patch-security_pkix_include_pkix_Result_h
patch-security_pkix_include_pkix_Time_h
patch-security_pkix_include_pkix_pkixtypes_h
patch-security_pkix_lib_pkixbuild_cpp
patch-security_pkix_lib_pkixtime_cpp
patch-tbb-tests_browser_ini
patch-tbb-tests_browser_tor_TB4_js
patch-tbb-tests_browser_tor_bug2950_js
patch-tbb-tests_browser_tor_bug4902_js
patch-tbb-tests_mochitest_ini
patch-tbb-tests_moz_build
patch-tbb-tests_test_tor_bug2874_html
patch-tbb-tests_test_tor_bug2875_html
patch-tbb-tests_test_tor_bug4755_html
patch-tbb-tests_test_tor_bug5856_html
patch-testing_config_mozharness_android_arm_config_py
patch-testing_config_mozharness_mac_config_py
patch-testing_config_tooltool-manifests_androidarm_releng_manifest
patch-testing_config_tooltool-manifests_androidx86_releng_manifest
patch-testing_config_tooltool-manifests_linux32_releng_manifest
patch-testing_config_tooltool-manifests_linux64_releng_manifest
patch-testing_config_tooltool-manifests_macosx64_releng_manifest
patch-testing_config_tooltool-manifests_win32_releng_manifest
patch-testing_marionette_client_marionette_geckoinstance_py
patch-testing_marionette_client_marionette_marionette_py
patch-testing_marionette_client_marionette_runner_base_py
patch-testing_mochitest_browser-test_js
patch-testing_mochitest_tests_SimpleTest_EventUtils_js
patch-testing_mozbase_mozrunner_mozrunner_local_py
patch-testing_mozbase_mozsystemmonitor_mozsystemmonitor_resourcemonitor_py
patch-testing_profiles_prefs_general_js
patch-testing_testsuite-targets_mk
patch-toolkit_components_contentprefs_nsContentPrefService_js
patch-toolkit_components_crashes_CrashManagerTest_jsm
patch-toolkit_components_crashes_tests_xpcshell_test_crash_manager_js
patch-toolkit_components_crashes_tests_xpcshell_xpcshell_ini
patch-toolkit_components_places_tests_browser_browser_bug248970_js
patch-toolkit_components_places_tests_browser_head_js
patch-toolkit_components_telemetry_Histograms_json
patch-toolkit_crashreporter_google-breakpad_src_google_breakpad_common_breakpad_types_h
patch-toolkit_library_dependentlibs_py
patch-toolkit_modules_Sqlite_jsm
patch-toolkit_modules_debug_js
patch-toolkit_mozapps_extensions_content_extensions_js
patch-toolkit_mozapps_extensions_content_extensions_xul
patch-toolkit_mozapps_extensions_internal_PluginProvider_jsm
patch-toolkit_mozapps_extensions_moz_build
patch-toolkit_mozapps_extensions_test_browser_head_js
patch-toolkit_mozapps_plugins_content_pluginProblem_xml
patch-toolkit_mozapps_update_common_updatehelper_cpp
patch-toolkit_mozapps_update_content_updates_js
patch-toolkit_mozapps_update_jar_mn
patch-toolkit_mozapps_update_nsUpdateService_js
patch-toolkit_mozapps_update_tests_Makefile_in
patch-toolkit_mozapps_update_tests_TestAUSHelper_cpp
patch-toolkit_mozapps_update_tests_moz_build
patch-toolkit_mozapps_update_updater_Makefile_in
patch-toolkit_mozapps_update_updater_archivereader_cpp
patch-toolkit_mozapps_update_updater_gen_cert_header_py
patch-toolkit_mozapps_update_updater_moz_build
patch-toolkit_mozapps_update_updater_release_primary_der
patch-toolkit_mozapps_update_updater_release_secondary_der
patch-toolkit_mozapps_update_updater_updater_cpp
patch-toolkit_mozapps_update_updater_updater_rc
patch-toolkit_system_gnome_nsAlertsIconListener_cpp
patch-toolkit_toolkit_mozbuild
patch-toolkit_webapps_tests_chrome_ini
patch-toolkit_xre_nsAppRunner_cpp
patch-toolkit_xre_nsEmbedFunctions_cpp
patch-toolkit_xre_nsUpdateDriver_cpp
patch-toolkit_xre_nsXREDirProvider_cpp
patch-toolkit_xre_nsXREDirProvider_h
patch-tools_update-packaging_Makefile_in
patch-tools_update-packaging_common_sh
patch-tools_update-packaging_make_full_update_sh
patch-tools_update-packaging_make_incremental_update_sh
patch-widget_LookAndFeel_h
patch-widget_cocoa_nsAppShell_mm
patch-widget_cocoa_nsChildView_mm
patch-widget_cocoa_nsCocoaFeatures_h
patch-widget_cocoa_nsCocoaFeatures_mm
patch-widget_cocoa_nsCocoaUtils_mm
patch-widget_cocoa_nsMenuItemIconX_mm
patch-widget_windows_nsAppShell_cpp
patch-widget_xpwidgets_nsTransferable_cpp
patch-widget_xpwidgets_nsTransferable_h
patch-widget_xpwidgets_nsXPLookAndFeel_cpp
patch-widget_xpwidgets_nsXPLookAndFeel_h
patch-xpcom_base_nsCycleCollector_cpp
patch-xpcom_build_nsXPComInit_cpp
patch-xpcom_io_moz_build
patch-xpcom_io_nsAppFileLocationProvider_cpp
patch-xpcom_reflect_xptcall_src_md_unix_xptcinvoke_arm_cpp
*** List of 500 patches after diffsplit can deal w/bins, new files
patch-Makefile_in
patch-_gitignore
patch-accessible_src_jsat_EventManager_jsm
patch-browser_app_Makefile_in
patch-browser_app_blocklist_xml
patch-browser_app_profile_firefox_js
patch-browser_base_content_aboutDialog_js
patch-browser_base_content_browser-plugins_js
patch-browser_base_content_browser_js
patch-browser_base_content_browser_xul
patch-browser_base_content_newtab_newTab_css
patch-browser_base_content_test_general_browser_aboutHome_js
patch-browser_base_content_test_general_browser_ini
patch-browser_base_content_test_general_browser_keywordSearch_js
patch-browser_branding_official_configure_sh
patch-browser_branding_official_locales_en-US_brand_dtd
patch-browser_branding_official_locales_en-US_brand_properties
patch-browser_branding_official_pref_firefox-branding_js
patch-browser_components_search_test_browser_426329_js
patch-browser_components_search_test_browser_google_behavior_js
patch-browser_components_search_test_browser_google_js
patch-browser_components_search_test_head_js
patch-browser_components_sessionstore_src_SessionStorage_jsm
patch-browser_components_tabview_test_browser_tabview_bug598600_js
patch-browser_components_tabview_test_browser_tabview_bug651311_js
patch-browser_components_tabview_test_browser_tabview_bug712203_js
patch-browser_components_tabview_test_head_js
patch-browser_config_mozconfigs_linux32_debug
patch-browser_config_mozconfigs_linux64_debug
patch-browser_config_mozconfigs_linux64_debug-nonunified
patch-browser_config_mozconfigs_linux64_debug-static-analysis-clang
patch-browser_config_mozconfigs_linux64_nightly-nonunified
patch-browser_config_mozconfigs_macosx-universal_nightly-nonunified
patch-browser_config_mozconfigs_macosx64_debug-nonunified
patch-browser_config_mozconfigs_win32_beta
patch-browser_config_mozconfigs_win32_debug
patch-browser_config_mozconfigs_win32_debug-nonunified
patch-browser_config_mozconfigs_win32_nightly
patch-browser_config_mozconfigs_win32_nightly-nonunified
patch-browser_config_mozconfigs_win32_release
patch-browser_config_mozconfigs_win64_beta
patch-browser_config_mozconfigs_win64_debug
patch-browser_config_mozconfigs_win64_nightly
patch-browser_config_mozconfigs_win64_release
patch-browser_config_version_txt
patch-browser_confvars_sh
patch-browser_devtools_styleeditor_test_head_js
patch-browser_installer_Makefile_in
patch-browser_installer_package-manifest_in
patch-browser_installer_removed-files_in
patch-browser_installer_windows_nsis_shared_nsh
patch-browser_locales_en-US_chrome_browser_browser_properties
patch-browser_locales_en-US_searchplugins_bing_xml
patch-browser_locales_en-US_searchplugins_google_xml
patch-browser_locales_en-US_searchplugins_list_txt
patch-browser_themes_linux_browser_css
patch-browser_themes_linux_jar_mn
patch-browser_themes_osx_browser_css
patch-browser_themes_osx_jar_mn
patch-browser_themes_windows_browser_css
patch-browser_themes_windows_jar_mn
patch-build_automation_py_in
patch-build_automationutils_py
patch-build_mach_bootstrap_py
patch-build_macosx_mozconfig_common
patch-build_mozconfig_common
patch-build_unix_mozconfig_asan
patch-build_unix_mozconfig_linux
patch-caps_src_nsScriptSecurityManager_cpp
patch-caps_tests_mochitest_test_bug995943_xul
patch-client_mk
patch-config_createprecomplete_py
patch-config_milestone_txt
patch-config_version_mk
patch-configure_in
patch-content_base_public_DirectionalityUtils_h
patch-content_base_src_DirectionalityUtils_cpp
patch-content_base_src_ThirdPartyUtil_cpp
patch-content_base_src_ThirdPartyUtil_h
patch-content_base_src_nsContentUtils_cpp
patch-content_base_src_nsDocument_cpp
patch-content_base_src_nsGenericDOMDataNode_cpp
patch-content_base_src_nsScriptLoader_cpp
patch-content_base_src_nsXMLHttpRequest_h
patch-content_base_test_mochitest_ini
patch-content_canvas_src_CanvasGradient_h
patch-content_canvas_src_CanvasRenderingContext2D_cpp
patch-content_canvas_src_CanvasRenderingContext2D_h
patch-content_canvas_src_CanvasUtils_cpp
patch-content_canvas_src_CanvasUtils_h
patch-content_canvas_src_ImageEncoder_cpp
patch-content_canvas_src_ImageEncoder_h
patch-content_canvas_test_webgl-conformance_skipped_tests_android_txt
patch-content_canvas_test_webgl-conformance_skipped_tests_android_x86_txt
patch-content_canvas_test_webgl-conformance_skipped_tests_linux_mesa_txt
patch-content_canvas_test_webgl-conformance_skipped_tests_linux_txt
patch-content_html_content_public_HTMLCanvasElement_h
patch-content_html_content_src_HTMLCanvasElement_cpp
patch-content_html_content_test_file_iframe_sandbox_e_if6_html
patch-content_html_content_test_file_iframe_sandbox_form_pass_html
patch-content_media_AudioEventTimeline_h
patch-content_media_MediaCache_cpp
patch-content_media_test_test_load_candidates_html
patch-content_media_webaudio_OscillatorNode_cpp
patch-content_media_webaudio_test_test_periodicWave_html
patch-content_media_webm_WebMReader_cpp
patch-content_svg_content_src_DOMSVGLengthList_cpp
patch-content_svg_content_src_DOMSVGLength_cpp
patch-content_svg_content_src_DOMSVGLength_h
patch-content_svg_content_src_DOMSVGPointList_cpp
patch-content_svg_content_src_DOMSVGPoint_h
patch-content_svg_content_src_SVGSVGElement_cpp
patch-content_svg_content_src_SVGSVGElement_h
patch-content_svg_content_src_nsISVGPoint_h
patch-content_svg_content_test_test_SVGLengthList_xhtml
patch-content_svg_content_test_test_SVGPointList_xhtml
patch-docshell_base_nsDocShell_cpp
patch-docshell_test_test_bug529119-2_html
patch-dom_alarm_AlarmsManager_js
patch-dom_alarm_test_mochitest_ini
patch-dom_base_Navigator_cpp
patch-dom_base_Navigator_h
patch-dom_base_WindowNamedPropertiesHandler_cpp
patch-dom_base_WindowNamedPropertiesHandler_h
patch-dom_base_nsDOMClassInfo_cpp
patch-dom_base_nsGlobalWindow_cpp
patch-dom_base_nsGlobalWindow_h
patch-dom_base_nsPerformance_cpp
patch-dom_base_nsScreen_cpp
patch-dom_base_nsScreen_h
patch-dom_bindings_Bindings_conf
patch-dom_bindings_Codegen_py
patch-dom_bindings_DOMJSProxyHandler_cpp
patch-dom_bindings_DOMJSProxyHandler_h
patch-dom_bindings_test_mochitest_ini
patch-dom_browser-element_BrowserElementChildPreload_js
patch-dom_events_Event_cpp
patch-dom_events_test_test_bug432698_html
patch-dom_interfaces_storage_nsIDOMStorageManager_idl
patch-dom_media_MediaManager_cpp
patch-dom_media_MediaManager_h
patch-dom_plugins_base_moz_build
patch-dom_plugins_base_nsPluginHost_cpp
patch-dom_plugins_base_nsPluginHost_h
patch-dom_plugins_ipc_PluginModuleChild_cpp
patch-dom_plugins_ipc_PluginModuleParent_cpp
patch-dom_plugins_ipc_PluginProcessChild_cpp
patch-dom_plugins_test_mochitest_dialog_watcher_js
patch-dom_plugins_test_mochitest_test_hangui_xul
patch-dom_src_storage_DOMStorageCache_cpp
patch-dom_src_storage_DOMStorageCache_h
patch-dom_src_storage_DOMStorageManager_cpp
patch-dom_src_storage_DOMStorageManager_h
patch-dom_tests_mochitest_beacon_mochitest_ini
patch-dom_tests_mochitest_localstorage_mochitest_ini
patch-dom_workers_Navigator_cpp
patch-dom_workers_Navigator_h
patch-dom_workers_RuntimeService_cpp
patch-dom_workers_RuntimeService_h
patch-dom_workers_WorkerScope_cpp
patch-dom_workers_XMLHttpRequest_cpp
patch-dom_workers_test_chrome_ini
patch-dom_workers_test_mochitest_ini
patch-dom_workers_test_test_multi_sharedWorker_lifetimes_html
patch-embedding_browser_webBrowser_nsContextMenuInfo_cpp
patch-embedding_components_windowwatcher_src_nsWindowWatcher_cpp
patch-extensions_auth_nsHttpNegotiateAuth_cpp
patch-extensions_cookie_nsCookiePermission_cpp
patch-extensions_cookie_nsPermissionManager_cpp
patch-extensions_cookie_test_unit_test_cookies_read_js
patch-gfx_2d_Blur_cpp
patch-gfx_2d_Blur_h
patch-gfx_2d_DrawTargetCairo_cpp
patch-gfx_layers_basic_BasicLayerManager_cpp
patch-gfx_thebes_gfxBlur_cpp
patch-gfx_thebes_gfxFont_cpp
patch-gfx_thebes_gfxPangoFonts_cpp
patch-gfx_thebes_gfxUserFontSet_cpp
patch-gfx_thebes_gfxUserFontSet_h
patch-image_public_imgILoader_idl
patch-image_src_ImageURL_h
patch-image_src_imgFrame_cpp
patch-image_src_imgLoader_cpp
patch-image_src_imgLoader_h
patch-image_src_imgRequest_cpp
patch-image_src_imgRequest_h
patch-image_test_mochitest_test_animSVGImage2_html
patch-ipc_glue_MessageChannel_cpp
patch-ipc_glue_MessageChannel_h
patch-ipc_glue_WindowsMessageLoop_cpp
patch-ipc_glue_WindowsMessageLoop_h
patch-ipc_glue_moz_build
patch-js_public_Class_h
patch-js_src_assembler_assembler_MacroAssemblerX86Common_cpp
patch-js_src_builtin_Intl_cpp
patch-js_src_configure_in
patch-js_src_jit-test_lib_asm_js
patch-js_src_jit-test_tests_asm_js_testBullet_js
patch-js_src_jit-test_tests_asm_js_testCaching_js
patch-js_src_jit-test_tests_asm_js_testHeapAccess_js
patch-js_src_jit-test_tests_asm_js_testSource_js
patch-js_src_jit-test_tests_asm_js_testStackWalking_js
patch-js_src_jit-test_tests_debug_optimized-out-01_js
patch-js_src_jit_CompileInfo_h
patch-js_src_jit_IonAnalysis_cpp
patch-js_src_jit_IonBuilder_cpp
patch-js_src_jit_IonMacroAssembler_cpp
patch-js_src_jit_Ion_cpp
patch-js_src_jit_JitCompartment_h
patch-js_src_jit_LIR_h
patch-js_src_jit_MIR_cpp
patch-js_src_jit_VMFunctions_h
patch-js_src_jit_arm_MacroAssembler-arm_cpp
patch-js_src_jit_arm_MacroAssembler-arm_h
patch-js_src_jit_arm_Trampoline-arm_cpp
patch-js_src_jit_mips_MacroAssembler-mips_cpp
patch-js_src_jit_mips_MacroAssembler-mips_h
patch-js_src_jit_mips_Trampoline-mips_cpp
patch-js_src_jit_shared_MacroAssembler-x86-shared_h
patch-js_src_jit_x64_MacroAssembler-x64_cpp
patch-js_src_jit_x64_MacroAssembler-x64_h
patch-js_src_jit_x64_Trampoline-x64_cpp
patch-js_src_jit_x86_MacroAssembler-x86_cpp
patch-js_src_jit_x86_MacroAssembler-x86_h
patch-js_src_jit_x86_Trampoline-x86_cpp
patch-js_src_js-config_h_in
patch-js_src_jsapi-tests_moz_build
patch-js_src_jsapi-tests_testDefineGetterSetterNonEnumerable_cpp
patch-js_src_jsapi_cpp
patch-js_src_jsapi_h
patch-js_src_jsfriendapi_h
patch-js_src_jsobj_cpp
patch-js_src_jsobjinlines_h
patch-js_src_jsproxy_cpp
patch-js_src_jsworkers_cpp
patch-js_src_shell_js_cpp
patch-js_src_vm_Shape_cpp
patch-js_src_vm_Shape_h
patch-js_xpconnect_src_XPCWrappedNativeJSOps_cpp
patch-js_xpconnect_tests_mochitest_mochitest_ini
patch-js_xpconnect_tests_mochitest_test_bug790732_html
patch-js_xpconnect_wrappers_XrayWrapper_cpp
patch-layout_base_RestyleManager_cpp
patch-layout_base_nsIPresShell_h
patch-layout_base_nsLayoutUtils_cpp
patch-layout_base_nsLayoutUtils_h
patch-layout_base_nsPresContext_cpp
patch-layout_base_nsPresContext_h
patch-layout_base_nsPresShell_cpp
patch-layout_base_tests_bug1007065-1-ref_html
patch-layout_base_tests_bug1007065-1_html
patch-layout_generic_nsFrame_cpp
patch-layout_generic_nsImageFrame_cpp
patch-layout_generic_test_mochitest_ini
patch-layout_generic_test_test_bug470212_html
patch-layout_style_nsCSSParser_cpp
patch-layout_style_nsComputedDOMStyle_cpp
patch-layout_style_nsFontFaceLoader_cpp
patch-layout_style_nsFontFaceLoader_h
patch-layout_style_nsMediaFeatures_cpp
patch-layout_style_nsRuleNode_cpp
patch-mach
patch-media_libcubeb_src_cubeb_wasapi_cpp
patch-media_libcubeb_tests_test_sanity_cpp
patch-media_libnestegg_include_nestegg-stdint_h
patch-media_libnestegg_src_nestegg_c
patch-media_libspeex_resampler_src_resample_c
patch-media_libvpx_vp9_decoder_vp9_decodframe_c
patch-media_libyuv_source_cpu_id_cc
patch-media_mtransport_test_moz_build
patch-media_mtransport_third_party_nICEr_src_stun_stun_codec_c
patch-media_mtransport_third_party_nrappkit_src_util_byteorder_c
patch-media_mtransport_third_party_nrappkit_src_util_byteorder_h
patch-media_webrtc_signaling_src_peerconnection_PeerConnectionImpl_cpp
patch-media_webrtc_signaling_src_peerconnection_PeerConnectionImpl_h
patch-media_webrtc_signaling_src_peerconnection_PeerConnectionMedia_cpp
patch-media_webrtc_signaling_src_peerconnection_PeerConnectionMedia_h
patch-media_webrtc_signaling_src_sipcc_core_gsm_h_fsm_h
patch-media_webrtc_signaling_src_sipcc_core_sdp_sdp_attr_c
patch-media_webrtc_signaling_src_sipcc_core_sdp_sdp_main_c
patch-media_webrtc_signaling_test_sdp_unittests_cpp
patch-memory_mozalloc_VolatileBuffer_h
patch-mfbt_Char16_h
patch-mobile_android_base_Makefile_in
patch-mobile_android_base_tests_BaseTest_java
patch-mobile_android_base_tests_testSearchSuggestions_java
patch-mobile_android_components_HelperAppDialog_js
patch-mobile_android_config_mozconfigs_common
patch-mobile_android_confvars_sh
patch-mobile_locales_en-US_searchplugins_google_xml
patch-modules_libjar_nsJARChannel_cpp
patch-modules_libmar_moz_build
patch-modules_libmar_sign_mar_sign_c
patch-modules_libmar_sign_moz_build
patch-modules_libmar_src_mar_cmdline_h
patch-modules_libmar_src_mar_h
patch-modules_libmar_src_mar_private_h
patch-modules_libmar_tool_Makefile_in
patch-modules_libmar_tool_mar_c
patch-modules_libmar_tool_moz_build
patch-modules_libmar_verify_cryptox_c
patch-modules_libmar_verify_cryptox_h
patch-modules_libmar_verify_mar_verify_c
patch-modules_libmar_verify_moz_build
patch-modules_libpref_src_init_all_js
patch-mozglue_build_WindowsDllBlocklist_cpp
patch-netwerk_base_public_mozIThirdPartyUtil_idl
patch-netwerk_base_public_nsICachingChannel_idl
patch-netwerk_base_public_nsIProtocolProxyCallback_idl
patch-netwerk_base_public_nsIProtocolProxyFilter_idl
patch-netwerk_base_public_nsIProtocolProxyService2_idl
patch-netwerk_base_public_nsIProtocolProxyService_idl
patch-netwerk_base_public_nsIProxyInfo_idl
patch-netwerk_base_public_security-prefs_js
patch-netwerk_base_src_nsIOService_cpp
patch-netwerk_base_src_nsPACMan_cpp
patch-netwerk_base_src_nsPACMan_h
patch-netwerk_base_src_nsProtocolProxyService_cpp
patch-netwerk_base_src_nsProtocolProxyService_h
patch-netwerk_base_src_nsProxyInfo_cpp
patch-netwerk_base_src_nsProxyInfo_h
patch-netwerk_base_src_nsSocketTransport2_cpp
patch-netwerk_base_src_nsSocketTransport2_h
patch-netwerk_base_src_nsStandardURL_cpp
patch-netwerk_cache_nsCacheService_cpp
patch-netwerk_dns_effective_tld_names_dat
patch-netwerk_dns_nsDNSService2_cpp
patch-netwerk_dns_nsDNSService2_h
patch-netwerk_protocol_ftp_nsFtpConnectionThread_cpp
patch-netwerk_protocol_http_HttpBaseChannel_cpp
patch-netwerk_protocol_http_HttpBaseChannel_h
patch-netwerk_protocol_http_nsHttpChannel_cpp
patch-netwerk_protocol_http_nsHttpChannel_h
patch-netwerk_protocol_http_nsHttpConnectionInfo_cpp
patch-netwerk_protocol_http_nsHttpConnectionInfo_h
patch-netwerk_protocol_http_nsHttpConnectionMgr_cpp
patch-netwerk_protocol_http_nsHttpConnectionMgr_h
patch-netwerk_protocol_http_nsHttpConnection_cpp
patch-netwerk_protocol_http_nsHttpHandler_cpp
patch-netwerk_protocol_http_nsHttpHandler_h
patch-netwerk_protocol_http_nsHttpNTLMAuth_cpp
patch-netwerk_protocol_http_nsHttpPipeline_cpp
patch-netwerk_protocol_http_nsHttpPipeline_h
patch-netwerk_protocol_http_nsHttpTransaction_cpp
patch-netwerk_protocol_http_nsHttpTransaction_h
patch-netwerk_protocol_http_nsIHttpChannel_idl
patch-netwerk_protocol_viewsource_nsViewSourceChannel_cpp
patch-netwerk_protocol_websocket_WebSocketChannel_cpp
patch-netwerk_sctp_datachannel_DataChannelProtocol_h
patch-netwerk_sctp_datachannel_DataChannel_cpp
patch-netwerk_sctp_src_moz_build
patch-netwerk_sctp_src_netinet_sctp_callout_c
patch-netwerk_sctp_src_netinet_sctp_callout_h
patch-netwerk_sctp_src_netinet_sctp_usrreq_c
patch-netwerk_sctp_src_user_sctp_timer_iterate_c
patch-netwerk_socket_nsISocketProvider_idl
patch-netwerk_socket_nsSOCKSIOLayer_cpp
patch-netwerk_socket_nsSOCKSIOLayer_h
patch-netwerk_socket_nsSOCKSSocketProvider_cpp
patch-netwerk_socket_nsUDPSocketProvider_cpp
patch-netwerk_test_browser_browser_ini
patch-netwerk_test_unit_test_auth_proxy_js
patch-parser_html_nsHtml5Parser_cpp
patch-parser_html_nsHtml5Parser_h
patch-parser_html_nsHtml5StreamParser_cpp
patch-parser_html_nsHtml5StreamParser_h
patch-parser_html_nsHtml5TreeBuilderCppSupplement_h
patch-parser_html_nsHtml5TreeBuilderHSupplement_h
patch-parser_html_nsHtml5TreeOpExecutor_cpp
patch-parser_html_nsHtml5TreeOpExecutor_h
patch-parser_html_nsHtml5TreeOperation_cpp
patch-parser_html_nsHtml5TreeOperation_h
patch-python_mach_mach_main_py
patch-python_mach_mach_test_test_conditions_py
patch-python_mozbuild_mozbuild_base_py
patch-python_mozbuild_mozbuild_controller_building_py
patch-python_mozbuild_mozbuild_mach_commands_py
patch-python_mozbuild_mozbuild_test_test_base_py
patch-security_apps_AppTrustDomain_h
patch-security_build_Makefile_in
patch-security_build_moz_build
patch-security_certverifier_CertVerifier_cpp
patch-security_certverifier_CertVerifier_h
patch-security_certverifier_NSSCertDBTrustDomain_cpp
patch-security_certverifier_NSSCertDBTrustDomain_h
patch-security_certverifier_moz_build
patch-security_manager_boot_src_moz_build
patch-security_manager_boot_src_nsSTSPreloadList_errors
patch-security_manager_boot_src_nsSTSPreloadList_inc
patch-security_manager_ssl_src_NSSErrorsService_cpp
patch-security_manager_ssl_src_SSLServerCertVerification_cpp
patch-security_manager_ssl_src_SharedCertVerifier_h
patch-security_manager_ssl_src_nsCMS_cpp
patch-security_manager_ssl_src_nsNSSCertificateDB_cpp
patch-security_manager_ssl_src_nsNSSCertificate_cpp
patch-security_manager_ssl_src_nsNSSComponent_cpp
patch-security_manager_ssl_src_nsNSSIOLayer_cpp
patch-security_manager_ssl_src_nsNSSIOLayer_h
patch-security_manager_ssl_src_nsSSLSocketProvider_cpp
patch-security_manager_ssl_src_nsTLSSocketProvider_cpp
patch-security_manager_ssl_src_nsUsageArrayHelper_cpp
patch-security_manager_ssl_tests_unit_head_psm_js
patch-security_manager_ssl_tests_unit_test_cert_overrides_js
patch-security_manager_ssl_tests_unit_tlsserver_cmd_BadCertServer_cpp
patch-security_manager_ssl_tests_unit_tlsserver_generate_certs_sh
patch-security_manager_ssl_tests_unit_xpcshell_ini
patch-security_nss_TAG-INFO
patch-security_nss_coreconf_coreconf_dep
patch-security_nss_lib_certhigh_ocsp_c
patch-security_nss_lib_cryptohi_secvfy_c
patch-security_nss_lib_freebl_ec_c
patch-security_nss_lib_freebl_rsa_c
patch-security_nss_lib_libpkix_pkix_pl_nss_module_pkix_pl_socket_c
patch-security_nss_lib_nss_nss_h
patch-security_nss_lib_softoken_pkcs11_c
patch-security_nss_lib_softoken_pkcs11c_c
patch-security_nss_lib_softoken_softkver_h
patch-security_nss_lib_ssl_SSLerrs_h
patch-security_nss_lib_ssl_ssl3con_c
patch-security_nss_lib_ssl_ssl3prot_h
patch-security_nss_lib_ssl_ssl_h
patch-security_nss_lib_ssl_sslerr_h
patch-security_nss_lib_ssl_sslimpl_h
patch-security_nss_lib_ssl_sslproto_h
patch-security_nss_lib_ssl_sslsock_c
patch-security_nss_lib_util_manifest_mn
patch-security_nss_lib_util_nssutil_def
patch-security_nss_lib_util_nssutil_h
patch-security_nss_tests_chains_chains_sh
patch-security_pkix_include_pkix_pkixtypes_h
patch-security_pkix_lib_pkixbuild_cpp
patch-testing_config_mozharness_android_arm_config_py
patch-testing_config_mozharness_mac_config_py
patch-testing_marionette_client_marionette_geckoinstance_py
patch-testing_marionette_client_marionette_marionette_py
patch-testing_marionette_client_marionette_runner_base_py
patch-testing_mochitest_browser-test_js
patch-testing_mochitest_tests_SimpleTest_EventUtils_js
patch-testing_mozbase_mozrunner_mozrunner_local_py
patch-testing_mozbase_mozsystemmonitor_mozsystemmonitor_resourcemonitor_py
patch-testing_profiles_prefs_general_js
patch-testing_testsuite-targets_mk
patch-toolkit_components_contentprefs_nsContentPrefService_js
patch-toolkit_components_crashes_CrashManagerTest_jsm
patch-toolkit_components_crashes_tests_xpcshell_test_crash_manager_js
patch-toolkit_components_crashes_tests_xpcshell_xpcshell_ini
patch-toolkit_components_places_tests_browser_browser_bug248970_js
patch-toolkit_components_places_tests_browser_head_js
patch-toolkit_components_telemetry_Histograms_json
patch-toolkit_crashreporter_google-breakpad_src_google_breakpad_common_breakpad_types_h
patch-toolkit_library_dependentlibs_py
patch-toolkit_modules_Sqlite_jsm
patch-toolkit_modules_debug_js
patch-toolkit_mozapps_extensions_content_extensions_js
patch-toolkit_mozapps_extensions_content_extensions_xul
patch-toolkit_mozapps_extensions_internal_PluginProvider_jsm
patch-toolkit_mozapps_extensions_moz_build
patch-toolkit_mozapps_extensions_test_browser_head_js
patch-toolkit_mozapps_plugins_content_pluginProblem_xml
patch-toolkit_mozapps_update_common_updatehelper_cpp
patch-toolkit_mozapps_update_content_updates_js
patch-toolkit_mozapps_update_jar_mn
patch-toolkit_mozapps_update_nsUpdateService_js
patch-toolkit_mozapps_update_tests_Makefile_in
patch-toolkit_mozapps_update_tests_TestAUSHelper_cpp
patch-toolkit_mozapps_update_tests_moz_build
patch-toolkit_mozapps_update_updater_Makefile_in
patch-toolkit_mozapps_update_updater_archivereader_cpp
patch-toolkit_mozapps_update_updater_moz_build
patch-toolkit_mozapps_update_updater_updater_cpp
patch-toolkit_mozapps_update_updater_updater_rc
patch-toolkit_system_gnome_nsAlertsIconListener_cpp
patch-toolkit_toolkit_mozbuild
patch-toolkit_webapps_tests_chrome_ini
patch-toolkit_xre_nsAppRunner_cpp
patch-toolkit_xre_nsEmbedFunctions_cpp
patch-toolkit_xre_nsUpdateDriver_cpp
patch-toolkit_xre_nsXREDirProvider_cpp
patch-toolkit_xre_nsXREDirProvider_h
patch-tools_update-packaging_Makefile_in
patch-tools_update-packaging_common_sh
patch-tools_update-packaging_make_full_update_sh
patch-tools_update-packaging_make_incremental_update_sh
patch-widget_LookAndFeel_h
patch-widget_cocoa_nsAppShell_mm
patch-widget_cocoa_nsChildView_mm
patch-widget_cocoa_nsCocoaFeatures_h
patch-widget_cocoa_nsCocoaFeatures_mm
patch-widget_cocoa_nsCocoaUtils_mm
patch-widget_cocoa_nsMenuItemIconX_mm
patch-widget_windows_nsAppShell_cpp
patch-widget_xpwidgets_nsTransferable_cpp
patch-widget_xpwidgets_nsTransferable_h
patch-widget_xpwidgets_nsXPLookAndFeel_cpp
patch-widget_xpwidgets_nsXPLookAndFeel_h
patch-xpcom_base_nsCycleCollector_cpp
patch-xpcom_build_nsXPComInit_cpp
patch-xpcom_io_moz_build
patch-xpcom_io_nsAppFileLocationProvider_cpp
patch-xpcom_reflect_xptcall_src_md_unix_xptcinvoke_arm_cpp
*** Removed patches and why

**** Build system tweaks that don't apply to us:

patch-Makefile_in
patch-browser_installer_Makefile_in 
patch-_gitignore
patch-browser_config_mozconfigs_linux32_debug
patch-browser_config_mozconfigs_linux64_debug
patch-browser_config_mozconfigs_linux64_debug-nonunified
patch-browser_config_mozconfigs_linux64_debug-static-analysis-clang
patch-browser_config_mozconfigs_linux64_nightly-nonunified
patch-browser_config_mozconfigs_macosx-universal_nightly-nonunified
patch-browser_config_mozconfigs_macosx64_debug-nonunified
patch-browser_config_mozconfigs_win32_debug
patch-browser_config_mozconfigs_win32_debug-nonunified
patch-browser_config_mozconfigs_win32_nightly-nonunified
patch-browser_config_mozconfigs_win64_debug
patch-build_automation_py_in
patch-build_automationutils_py
patch-build_macosx_mozconfig_common
patch-build_mozconfig_common
patch-build_unix_mozconfig_asan
patch-build_unix_mozconfig_linux
patch-client_mk
patch-python_mozbuild_mozbuild_mach_commands_py
patch-tools_update-packaging_Makefile_in
patch-toolkit_toolkit_mozbuild

** 2015-02-23
My first attempt was a dismal failure.  I hacked diffsplit.pl to
handle non-git diffs and tried again, this time starting from the
mozilla-esr distfile that the OpenBSD ports system downloads and
comparing against my tor-browser git repo.

*** new patch set based on actual distfile for esr vs. tor-browser git repo
patch-_gitignore
patch-_hgignore
patch-_hgtags
patch-_mozconfig
patch-_mozconfig-asan
patch-_mozconfig-mac
patch-_mozconfig-mingw
patch-addon-sdk_source__hgignore
patch-addon-sdk_source__hgtags
patch-browser_app_Makefile_in
patch-browser_app_profile_000-tor-browser_js
patch-browser_app_profile_firefox_js
patch-browser_base_content_aboutDialog_js
patch-browser_base_content_browser-plugins_js
patch-browser_base_content_browser_js
patch-browser_base_content_browser_xul
patch-browser_branding_official_configure_sh
patch-browser_branding_official_locales_en-US_brand_dtd
patch-browser_branding_official_locales_en-US_brand_properties
patch-browser_branding_official_pref_firefox-branding_js
patch-browser_components_sessionstore_src_SessionStorage_jsm
patch-browser_confvars_sh
patch-browser_installer_Makefile_in
patch-browser_installer_package-manifest_in
patch-browser_locales_en-US_chrome_browser_browser_properties
patch-browser_locales_en-US_searchplugins_bing_xml
patch-browser_locales_en-US_searchplugins_disconnect_xml
patch-browser_locales_en-US_searchplugins_duckduckgo_xml
patch-browser_locales_en-US_searchplugins_list_txt
patch-browser_locales_en-US_searchplugins_startpage_xml
patch-browser_locales_en-US_searchplugins_youtube_xml
patch-browser_themes_linux_browser_css
patch-browser_themes_linux_canvas-popup_svg
patch-browser_themes_linux_jar_mn
patch-browser_themes_osx_browser_css
patch-browser_themes_osx_canvas-popup_svg
patch-browser_themes_osx_jar_mn
patch-browser_themes_windows_browser_css
patch-browser_themes_windows_canvas-popup_svg
patch-browser_themes_windows_jar_mn
patch-build_autoconf_altoptions_m4
patch-build_autoconf_mozconfig-find
patch-build_autoconf_mozconfig2client-mk
patch-build_autoconf_mozconfig2configure
patch-build_pymake__hgignore
patch-client_mk
patch-config_createprecomplete_py
patch-config_version_mk
patch-configure
patch-configure_in
patch-content_base_src_ThirdPartyUtil_cpp
patch-content_base_src_ThirdPartyUtil_h
patch-content_base_src_nsContentUtils_cpp
patch-content_canvas_src_CanvasGradient_h
patch-content_canvas_src_CanvasRenderingContext2D_cpp
patch-content_canvas_src_CanvasRenderingContext2D_h
patch-content_canvas_src_CanvasUtils_cpp
patch-content_canvas_src_CanvasUtils_h
patch-content_canvas_src_ImageEncoder_cpp
patch-content_canvas_src_ImageEncoder_h
patch-content_html_content_public_HTMLCanvasElement_h
patch-content_html_content_src_HTMLCanvasElement_cpp
patch-docshell_base_nsDocShell_cpp
patch-dom_base_Navigator_cpp
patch-dom_base_Navigator_h
patch-dom_base_nsDOMClassInfo_cpp
patch-dom_base_nsGlobalWindow_cpp
patch-dom_base_nsGlobalWindow_h
patch-dom_base_nsPerformance_cpp
patch-dom_base_nsScreen_cpp
patch-dom_base_nsScreen_h
patch-dom_bindings_Bindings_conf
patch-dom_events_Event_cpp
patch-dom_interfaces_storage_nsIDOMStorageManager_idl
patch-dom_plugins_base_moz_build
patch-dom_plugins_base_nsPluginHost_cpp
patch-dom_plugins_base_nsPluginHost_h
patch-dom_src_storage_DOMStorageCache_cpp
patch-dom_src_storage_DOMStorageCache_h
patch-dom_src_storage_DOMStorageManager_cpp
patch-dom_src_storage_DOMStorageManager_h
patch-dom_tests_mochitest_localstorage_firstPartyInner_html
patch-dom_tests_mochitest_localstorage_firstParty_html
patch-dom_tests_mochitest_localstorage_mochitest_ini
patch-dom_tests_mochitest_localstorage_test_localStorageByFirstParty_html
patch-dom_workers_Navigator_cpp
patch-dom_workers_Navigator_h
patch-dom_workers_RuntimeService_cpp
patch-dom_workers_RuntimeService_h
patch-dom_workers_WorkerScope_cpp
patch-dom_workers_test_bug1060621_worker_js
patch-dom_workers_test_bug1062920_worker_js
patch-dom_workers_test_chrome_ini
patch-dom_workers_test_mochitest_ini
patch-dom_workers_test_test_bug1060621_html
patch-dom_workers_test_test_bug1062920_html
patch-dom_workers_test_test_bug1062920_xul
patch-embedding_browser_webBrowser_nsContextMenuInfo_cpp
patch-embedding_components_windowwatcher_src_nsWindowWatcher_cpp
patch-extensions_auth_nsHttpNegotiateAuth_cpp
patch-extensions_cookie_nsCookiePermission_cpp
patch-extensions_cookie_nsPermissionManager_cpp
patch-gfx_thebes_gfxFont_cpp
patch-gfx_thebes_gfxPangoFonts_cpp
patch-gfx_thebes_gfxUserFontSet_cpp
patch-gfx_thebes_gfxUserFontSet_h
patch-image_public_imgILoader_idl
patch-image_src_ImageURL_h
patch-image_src_imgLoader_cpp
patch-image_src_imgLoader_h
patch-image_src_imgRequest_cpp
patch-image_src_imgRequest_h
patch-js_src_configure
patch-js_src_configure_in
patch-js_src_jsapi_cpp
patch-js_src_jsapi_h
patch-js_xpconnect_tests_mochitest_mochitest_ini
patch-js_xpconnect_tests_mochitest_test_bug790732_html
patch-layout_base_nsLayoutUtils_cpp
patch-layout_base_nsLayoutUtils_h
patch-layout_base_nsPresContext_cpp
patch-layout_base_nsPresContext_h
patch-layout_generic_nsFrame_cpp
patch-layout_generic_nsImageFrame_cpp
patch-layout_style_nsCSSParser_cpp
patch-layout_style_nsComputedDOMStyle_cpp
patch-layout_style_nsFontFaceLoader_cpp
patch-layout_style_nsFontFaceLoader_h
patch-layout_style_nsMediaFeatures_cpp
patch-layout_style_nsRuleNode_cpp
patch-media_libyuv_source_cpu_id_cc
patch-mfbt_Char16_h
patch-modules_libjar_nsJARChannel_cpp
patch-modules_libmar_moz_build
patch-modules_libmar_sign_mar_sign_c
patch-modules_libmar_sign_moz_build
patch-modules_libmar_src_mar_cmdline_h
patch-modules_libmar_src_mar_h
patch-modules_libmar_src_mar_private_h
patch-modules_libmar_tool_Makefile_in
patch-modules_libmar_tool_mar_c
patch-modules_libmar_tool_moz_build
patch-modules_libmar_verify_cryptox_c
patch-modules_libmar_verify_cryptox_h
patch-modules_libmar_verify_mar_verify_c
patch-modules_libmar_verify_moz_build
patch-modules_libpref_src_init_all_js
patch-mozglue_build_WindowsDllBlocklist_cpp
patch-netwerk_base_public_mozIThirdPartyUtil_idl
patch-netwerk_base_public_nsICachingChannel_idl
patch-netwerk_base_public_nsIProtocolProxyCallback_idl
patch-netwerk_base_public_nsIProtocolProxyFilter_idl
patch-netwerk_base_public_nsIProtocolProxyService2_idl
patch-netwerk_base_public_nsIProtocolProxyService_idl
patch-netwerk_base_public_nsIProxyInfo_idl
patch-netwerk_base_public_security-prefs_js
patch-netwerk_base_src_nsIOService_cpp
patch-netwerk_base_src_nsPACMan_cpp
patch-netwerk_base_src_nsPACMan_h
patch-netwerk_base_src_nsProtocolProxyService_cpp
patch-netwerk_base_src_nsProtocolProxyService_h
patch-netwerk_base_src_nsProxyInfo_cpp
patch-netwerk_base_src_nsProxyInfo_h
patch-netwerk_base_src_nsSocketTransport2_cpp
patch-netwerk_base_src_nsSocketTransport2_h
patch-netwerk_cache_nsCacheService_cpp
patch-netwerk_dns_nsDNSService2_cpp
patch-netwerk_dns_nsDNSService2_h
patch-netwerk_protocol_ftp_nsFtpConnectionThread_cpp
patch-netwerk_protocol_http_HttpBaseChannel_cpp
patch-netwerk_protocol_http_HttpBaseChannel_h
patch-netwerk_protocol_http_nsHttpChannel_cpp
patch-netwerk_protocol_http_nsHttpChannel_h
patch-netwerk_protocol_http_nsHttpConnectionInfo_cpp
patch-netwerk_protocol_http_nsHttpConnectionInfo_h
patch-netwerk_protocol_http_nsHttpConnectionMgr_cpp
patch-netwerk_protocol_http_nsHttpConnectionMgr_h
patch-netwerk_protocol_http_nsHttpConnection_cpp
patch-netwerk_protocol_http_nsHttpHandler_cpp
patch-netwerk_protocol_http_nsHttpHandler_h
patch-netwerk_protocol_http_nsHttpNTLMAuth_cpp
patch-netwerk_protocol_http_nsHttpPipeline_cpp
patch-netwerk_protocol_http_nsHttpPipeline_h
patch-netwerk_protocol_http_nsIHttpChannel_idl
patch-netwerk_protocol_viewsource_nsViewSourceChannel_cpp
patch-netwerk_protocol_websocket_WebSocketChannel_cpp
patch-netwerk_socket_nsISocketProvider_idl
patch-netwerk_socket_nsSOCKSIOLayer_cpp
patch-netwerk_socket_nsSOCKSIOLayer_h
patch-netwerk_socket_nsSOCKSSocketProvider_cpp
patch-netwerk_socket_nsUDPSocketProvider_cpp
patch-netwerk_test_browser_browser_cacheFirstParty_js
patch-netwerk_test_browser_browser_ini
patch-netwerk_test_browser_firstPartyGrandParent_html
patch-netwerk_test_browser_firstPartyParent_html
patch-netwerk_test_browser_thirdPartyChild_iframe_html
patch-netwerk_test_browser_thirdPartyChild_link_css
patch-netwerk_test_browser_thirdPartyChild_script_js
patch-netwerk_test_browser_thirdPartyChild_track_vtt
patch-netwerk_test_browser_thirdPartyChild_xhr_html
patch-nsprpub__cvsignore
patch-nsprpub_config__cvsignore
patch-nsprpub_lib__cvsignore
patch-nsprpub_lib_ds__cvsignore
patch-nsprpub_lib_libc__cvsignore
patch-nsprpub_lib_libc_include__cvsignore
patch-nsprpub_lib_libc_src__cvsignore
patch-nsprpub_lib_prstreams__cvsignore
patch-nsprpub_lib_prstreams_tests_testprstrm__cvsignore
patch-nsprpub_lib_tests__cvsignore
patch-nsprpub_pr__cvsignore
patch-nsprpub_pr_include__cvsignore
patch-nsprpub_pr_include_md__cvsignore
patch-nsprpub_pr_include_obsolete__cvsignore
patch-nsprpub_pr_include_private__cvsignore
patch-nsprpub_pr_src__cvsignore
patch-nsprpub_pr_src_bthreads__cvsignore
patch-nsprpub_pr_src_cplus__cvsignore
patch-nsprpub_pr_src_cplus_tests__cvsignore
patch-nsprpub_pr_src_io__cvsignore
patch-nsprpub_pr_src_linking__cvsignore
patch-nsprpub_pr_src_malloc__cvsignore
patch-nsprpub_pr_src_md__cvsignore
patch-nsprpub_pr_src_md_beos__cvsignore
patch-nsprpub_pr_src_md_os2__cvsignore
patch-nsprpub_pr_src_md_unix__cvsignore
patch-nsprpub_pr_src_md_windows__cvsignore
patch-nsprpub_pr_src_memory__cvsignore
patch-nsprpub_pr_src_misc__cvsignore
patch-nsprpub_pr_src_pthreads__cvsignore
patch-nsprpub_pr_src_threads__cvsignore
patch-nsprpub_pr_src_threads_combined__cvsignore
patch-nsprpub_pr_tests__cvsignore
patch-nsprpub_pr_tests_dll__cvsignore
patch-nsprpub_tools__cvsignore
patch-python_mozbuild_mozbuild_base_py
patch-python_mozbuild_mozbuild_mach_commands_py
patch-python_mozbuild_mozbuild_mozconfig_loader
patch-python_mozbuild_mozbuild_mozconfig_py
patch-python_mozbuild_mozbuild_test_backend_common_py
patch-python_mozbuild_mozbuild_test_frontend_test_emitter_py
patch-python_mozbuild_mozbuild_test_test_base_py
patch-python_mozbuild_mozbuild_test_test_mozconfig_py
patch-security_apps_AppTrustDomain_h
patch-security_build_Makefile_in
patch-security_build_moz_build
patch-security_certverifier_CertVerifier_cpp
patch-security_certverifier_CertVerifier_h
patch-security_certverifier_NSSCertDBTrustDomain_cpp
patch-security_certverifier_NSSCertDBTrustDomain_h
patch-security_certverifier_moz_build
patch-security_manager_boot_src_PublicKeyPinningService_cpp
patch-security_manager_boot_src_PublicKeyPinningService_cpp_rej
patch-security_manager_boot_src_PublicKeyPinningService_h
patch-security_manager_boot_src_StaticHPKPins_h
patch-security_manager_boot_src_moz_build
patch-security_manager_ssl_src_SSLServerCertVerification_cpp
patch-security_manager_ssl_src_SharedCertVerifier_h
patch-security_manager_ssl_src_nsCMS_cpp
patch-security_manager_ssl_src_nsNSSCertificateDB_cpp
patch-security_manager_ssl_src_nsNSSCertificate_cpp
patch-security_manager_ssl_src_nsNSSComponent_cpp
patch-security_manager_ssl_src_nsNSSIOLayer_cpp
patch-security_manager_ssl_src_nsNSSIOLayer_h
patch-security_manager_ssl_src_nsSSLSocketProvider_cpp
patch-security_manager_ssl_src_nsTLSSocketProvider_cpp
patch-security_manager_ssl_src_nsUsageArrayHelper_cpp
patch-security_manager_ssl_tests_unit_head_psm_js
patch-security_manager_ssl_tests_unit_test_cert_overrides_js
patch-security_manager_ssl_tests_unit_test_pinning_js
patch-security_manager_ssl_tests_unit_tlsserver_cmd_BadCertServer_cpp
patch-security_manager_ssl_tests_unit_tlsserver_generate_certs_sh
patch-security_manager_ssl_tests_unit_xpcshell_ini
patch-security_manager_tools_PreloadedHPKPins_json
patch-security_manager_tools_genHPKPStaticPins_js
patch-security_nss_doc__hgignore
patch-security_nss_doc_html__hgignore
patch-security_nss_lib_certhigh_ocsp_c
patch-security_nss_lib_libpkix_pkix_pl_nss_module_pkix_pl_socket_c
patch-security_nss_tests_pkcs11_netscape_trivial__cvsignore
patch-security_pkix_include_pkix_Result_h
patch-security_pkix_include_pkix_Time_h
patch-security_pkix_include_pkix_pkixtypes_h
patch-security_pkix_lib_pkixbuild_cpp
patch-security_pkix_lib_pkixtime_cpp
patch-tbb-tests_browser_ini
patch-tbb-tests_browser_tor_TB4_js
patch-tbb-tests_browser_tor_bug2950_js
patch-tbb-tests_browser_tor_bug4902_js
patch-tbb-tests_mochitest_ini
patch-tbb-tests_moz_build
patch-tbb-tests_test_tor_bug2874_html
patch-tbb-tests_test_tor_bug2875_html
patch-tbb-tests_test_tor_bug4755_html
patch-tbb-tests_test_tor_bug5856_html
patch-testing_mochitest_tests_SimpleTest_EventUtils_js
patch-testing_xpcshell_selftest_py
patch-toolkit_components_contentprefs_nsContentPrefService_js
patch-toolkit_components_telemetry_Histograms_json
patch-toolkit_crashreporter_google-breakpad_src_google_breakpad_common_breakpad_types_h
patch-toolkit_library_dependentlibs_py
patch-toolkit_modules_debug_js
patch-toolkit_mozapps_extensions_content_extensions_js
patch-toolkit_mozapps_extensions_content_extensions_xul
patch-toolkit_mozapps_extensions_internal_PluginProvider_jsm
patch-toolkit_mozapps_extensions_moz_build
patch-toolkit_mozapps_plugins_content_pluginProblem_xml
patch-toolkit_mozapps_update_common_updatehelper_cpp
patch-toolkit_mozapps_update_content_updates_js
patch-toolkit_mozapps_update_jar_mn
patch-toolkit_mozapps_update_nsUpdateService_js
patch-toolkit_mozapps_update_tests_Makefile_in
patch-toolkit_mozapps_update_tests_TestAUSHelper_cpp
patch-toolkit_mozapps_update_tests_moz_build
patch-toolkit_mozapps_update_updater_Makefile_in
patch-toolkit_mozapps_update_updater_archivereader_cpp
patch-toolkit_mozapps_update_updater_gen_cert_header_py
patch-toolkit_mozapps_update_updater_moz_build
patch-toolkit_mozapps_update_updater_updater_cpp
patch-toolkit_mozapps_update_updater_updater_rc
patch-toolkit_system_gnome_nsAlertsIconListener_cpp
patch-toolkit_toolkit_mozbuild
patch-toolkit_xre_nsAppRunner_cpp
patch-toolkit_xre_nsUpdateDriver_cpp
patch-toolkit_xre_nsXREDirProvider_cpp
patch-toolkit_xre_nsXREDirProvider_h
patch-tools_update-packaging_common_sh
patch-tools_update-packaging_make_full_update_sh
patch-tools_update-packaging_make_incremental_update_sh
patch-widget_LookAndFeel_h
patch-widget_cocoa_nsMenuItemIconX_mm
patch-widget_xpwidgets_nsTransferable_cpp
patch-widget_xpwidgets_nsTransferable_h
patch-widget_xpwidgets_nsXPLookAndFeel_cpp
patch-widget_xpwidgets_nsXPLookAndFeel_h
patch-xpcom_build_nsXPComInit_cpp
patch-xpcom_io_moz_build
patch-xpcom_io_nsAppFileLocationProvider_cpp
** 2015-03-04
on amd64 now:
make build 2>&1  6952.09s user 823.41s system 91% cpu 2:21:48.68 total
** 2015-03-18
Split common stuff out into a www/tbb module, although it could be
made more general and instead called www/ffextension or something.
The idea is that the Makefile for each tbb module that is a firefox
extension be as short as possible and all the guts of how to make a
ffext package is somewhere else.

First working package: torbutton

Unfortunately, still a lot of red in the output of ip-check.info's Tor
anonymity test.  I think NoScript might fix some of it, which is
weird...

Okay, so I just figured that out, several hours after I wrote the
above:

  # pkg_delete tor-browser
  tor-browser-4.0: ok
  Read shared items: ok
  --- -tor-browser-4.0 -------------------
  Error deleting directory /usr/local/lib/tor-browser-4.0: Directory not empty
  # ls /usr/local/lib/tor-browser-4.0
  TorBrowser
  # ls /usr/local/lib/tor-browser-4.0/TorBrowser 
  Data
  # ls /usr/local/lib/tor-browser-4.0/TorBrowser/Data
  Browser
  # ls /usr/local/lib/tor-browser-4.0/TorBrowser/Data/Browser 
  6kpkwhn9.default Caches           profiles.ini
  # ls -ld /usr/local/lib/tor-browser-4.0/TorBrowser/Data/Browser
  drwx------  4 attila  wheel  512 Mar 11 14:58 /usr/local/lib/tor-browser-4.0/TorBrowser/Data/Browser

What the fuck?  How was the browser able to do that?

The answer: /usr/local/lib/tor-browser-4.0 is group writable.
WRONG WRONG WRONG.
** 2015-03-19
I patched out this TorBrower shit in nsAppFileLocationProvider.cpp but
still it persists in dropping this shit in the same place.  However,
ktrace also gleaned this:

 15084 tor-browser NAMI  "/usr/local/lib/tor-browser-4.0/distribution/extensions"

So that's the place to drop them.  Have to fix this other shit now.
Irritating.

** 2015-03-20
Okay, I think I've got my shit straight now.

It turns out all of this ~/.mozilla stuff is dealt with in two completely
different places:
  1. xpcom/io/nsAppFileLocationProvider.cpp
  2. toolkit/xre/nsXREDirProvider.cpp
It was the second that I had missed before.  It turns out that even in
firefox esr34.0.1 there is a slight bug, or at least I think there is.
Nowhere in that second file is MOZ_USER_DIR consulted; instead under Unix
".mozilla" is hard-coded.  I patched this, but had to do it in an ugly way.
Because it appears that MOZ_USER_DIR (the cpp define) is not available
to me in the second place, instead I changed
  static const char* const sXR = ".mozilla";
to
  static const char* const sXR = "." MOZ_APP_NAME;
Since I know MOZ_APP_NAME is being set correctly, this should cause
tor-browser to store its profiles under ~/.tor-browser.  I would argue
that this is essential: you don't want tor-browser sharing the same
~/.mozilla that your non-tor-browser firefox uses.

As of 11:20am a new build is running that also patches the default tor
port to be correct under OpenBSD.  I'm now going back to packaging
noscript properly and then on to HTTPS Everywhere and Pluggable
Transports.

On that front, I've developed two ports modules that may end up
boiling away in the final product: www/tbb and www/firefox-addon.  The
second is a more generic version of the first, which is specific to
tbb addons.  This is because they don't follow the pattern of other
system-wide addons, where you interpose a directory whose name is the
GUID of the application (firefox, thunderbird, seamonkey).  In the
case of tor-browser for some reason the directory is different and
there is no GUID for firefox as a directory in the hierarchy; this is
probably because these extensions are normally stored in a profile,
which doesn't have this extra layer of directory.

Anyway, whatever.  I'm just trying to keep the makefiles short for the
actual addons, and so far I'm succeeding.  In the case of noscript I'm
using www/firefox-addon by default but switching to www/tbb if we're
building the tbb flavor; this should arrange to get a noscript-tbb
package built that installs in the right place for tbb but a
non-flavored noscript package that installs in the right place for
firefox/thunderbird.  I'll do the same thing with HTTPS Everywhere.
Not sure WTF pluggable transports even is yet.


Okay, we have a failure to communicate.

Now I have all major packages built.   The ~/.mozilla issue is STILL
unhandled, somehow... I don't know where that is hard-coded STILL
I guess.  But more importantly, tor-launcher trips on its own dick.

When I start with tor already running via the normal means:
  # /etc/rc.d/tor start
I get this:
  $ tor-browser
  Mar 20 16:09:43.291 [notice] Tor v0.2.5.10 (git-42b42605f8d8eac2) running on OpenBSD with Libevent 1.4.15-stable, OpenSSL LibreSSL 2.1 and Zlib 1.2.3.
  Mar 20 16:09:43.292 [notice] Tor can't help you if you use it wrong! Learn how to be safe at https://www.torproject.org/download/download#warning
  Mar 20 16:09:43.293 [notice] Read configuration file "/etc/tor/torrc".
  Mar 20 16:09:43.299 [notice] Opening Socks listener on 127.0.0.1:9050
  Mar 20 16:09:43.299 [warn] Could not bind to 127.0.0.1:9050: Address already in use. Is Tor already running?
  Mar 20 16:09:43.300 [warn] Failed to parse/validate config: Failed to bind one of the listener ports.
  Mar 20 16:09:43.300 [err] Reading config failed--see warnings above.

So apparently tor-launcher tries to bind to the control socket port
itself?  Why?

Shutting down tor doesn't fix it, it makes it worse, because we don't
want to run tor as me, we want to run tor as _tor:
  # /etc/rc.d/tor stop
Then:
  $ tor-browser
  Mar 20 16:13:48.319 [notice] Tor v0.2.5.10 (git-42b42605f8d8eac2) running on OpenBSD with Libevent 1.4.15-stable, OpenSSL LibreSSL 2.1 and Zlib 1.2.3.
  Mar 20 16:13:48.319 [notice] Tor can't help you if you use it wrong! Learn how to be safe at https://www.torproject.org/download/download#warning
  Mar 20 16:13:48.320 [notice] Read configuration file "/etc/tor/torrc".
  Mar 20 16:13:48.325 [notice] Opening Socks listener on 127.0.0.1:9050
  Mar 20 16:13:48.326 [notice] Caching new entry _tor for _tor
  Mar 20 16:13:48.326 [warn] Error setting groups to gid 566: "Operation not permitted".
  Mar 20 16:13:48.326 [warn] If you set the "User" option, you must start Tor as root.
  Mar 20 16:13:48.327 [warn] Failed to parse/validate config: Problem with User value. See logs for details.
  Mar 20 16:13:48.327 [err] Reading config failed--see warnings above.

So I guess what I have to do is package up a torrc that is used
internally in tor-launcher that is right for OpenBSD.  Joy.
** 2015-03-21 - 2015-03-27
Been lax with the notes, will try to fill in the gaps.

I've been almost entirely consumed by The Hunt For Dot Mozilla.  In
this awful drama I play the part of Sean Connery, the Russian
submarine captain, attempting to swim his way to freedom.  No, wait,
Sean Connery is an ACTOR.  Russian boat captains have names like Boris
and Ivan.
** 2015-03-30
Alright, finally, something reasonably solid, albeit with caveats.

Both torbutton and tor-launcher required substantial patching to get
them to work in the way we want.  The browser itself also needed one
more patch to finally s/.mozilla/.tor-browser/ and we are off to the
races.

In the end, this is how it works right now:
- tor-browser creates its profile directories under ~/.tor-browser,
  so e.g. this works:
          this.mTorFileBaseDir = Cc["@mozilla.org/file/directory_service;1"]
                   .getService(Ci.nsIProperties).get("DefProfRt",Ci.nsIFile);
  "DefProfRt" will return ~/.tor-browser now (well, actually, the real
  path)
- tor-launcher installs and uses /etc/tor/tbb-torrc as the torrc-defaults
  file combined with --ignore-missing-torrc and -f ~/.tor-browser/tor.rc
  The default tor data directory will be ~/.tor-browser/tor_data/
  This more or less makes the whole "bundle" idea reasonable sane in our
  context: all state that tor-browser cares about lives under ~/.tor-browser
  and you can tweak the tor config by munging ~/.tor-browser/tor.rc,
  which won't exist by default (but wait until pluggable transports)
- torbutton has had all of its automatic update checking disabled and
  its default ports changed to match tbb-torrc and the openbsd defaults
- tbb-noscript has been updated to the latest 2.6.9.19

I'm going to sync this to git because this actually kind of works now.
The tor-browser port itself needs to be updated to the latest 4.0.x
based on firefox esr35 since that's now in openbsd ports.  That will
be a little work.  Also need to finish HTTPS Everywhere and, hardest
of all, pluggable transports.  The latter is why I decided to push
through on making tor-launcher actually launch tor instead of just
relying on tor being running beforehand: we need to do torrc fu in
pluggable transports anyway, so we need to control tor and make it
read our own config somehow.

Not sure how this last bit is going to work out.  Am already midly
terrified by all the shit I can do to the local machine from JS via
XPCOM.
* tbb
** 2015-04-02
I'm switching everything in TBB to use the 915x port numbers for socks
and control by default, instead of patching everything to use the
OpenBSD default 905x port numbers.  This is because we want TBB to be
independent of whatever else is going on; if you are already running
for with the default config for some reason and then fire up TBB this
should not cause problems - two instances of tor, with two different
data directories listening on different sets of ports will be started.

It seemed to me that it would be even better if we let tor pick the
port numbers (at least the control port number, from which everything
else can be derived).  This is possible but would've required more
patches to tor-launcher because it doesn't know about this or send the
right command-line arguments to tor.  It's not a big patch and I might
decide to do this later but the only real benefit I can see is that
you could fire up multiple independent TBB sessions on the same
machine without clashing.  I don't think this is really important but
if someone does I'm willing to listen.

Sadly there is a port number backed into tor-browser which means
I have to wait another hour and a half for my tor-browser build
to finish.  I've also started to tighten things up and am making
sure I have the right versions of everything together for TBB 4.0.6.
It turns out I was careless before and was using versions of both
torbutton and tor-launcher that are very different than the ones
that go in the bundle.  This has been rectified in the latest
stuff and I've backed out all my port number patches.  Hopefully
this all goes together now.

There are also some mods that need to be made to tbb-noscript to make
it the same as the noscript that ships with the TBB and probably some
preferences tweaks that I've overlooked - there are a lot, in a lot of
places.

Beyond that we're down to HTTPSE and PT.

....

Alright, my build finished, the defaults were wrong in
tor-launcher/files/tbb-torrc but now that they're patched tor-browser
comes up green once again, using the tbb standard ports.

This is sort of a milestone.  We now have the right versions of the
core components all playing together as ports.
** 2015-04-03
I'm hung up on this whole extension-overrides.js business.  Nothing is
as simple as it seems and none of the documentation or blog posts I've
found end up having the winning answer.  I haven't tried everything
I've found yet but I'm starting to burn out on it a bit so I should
write some notes.

I thought before I charged ahead with more addons I would first make
sure I could get the ones I have done so far configured and working
properly.  This sounded like a 5min job to me yesterday but I'm still
at it.  The simple-sounding thing I thought I would address was making
sure noscript was configured as per the TBB.  They do this with a
bunch of js pref() fu in extension-overrides.js, which they drop into
the preferences subdirectory of the profile directory in the
pre-cooked profile they gen up with a sh script
(c.f. gitian-bundle.yml and the other yml files in
=gitian/descriptors/linux=).  They also cat more stuff onto this
(bridge_prefs.js) if Pluggable Transports (PT) is installed (and it
will be so we'll want to do this too).

I wanted to find a more general way to do this given that we have a
shared installation tree (=/usr/local/lib/tor-browser-x.y.z=) and
per-user profile dirs (=~/.tor-browser/foo.default=) like a normal
Mozillan app.  I've now read dozens of articles on MDN and (mostly
outdated) blog posts everywhere and so far everything everyone tells
me is wrong or doesn't work in this case.  Despite the many locations
I've tried dropping something like extension-overrides.js (or really
anything) under =/usr/local/lib/tor-browser-4.0.6= in the end it hasn't
worked yet.  I'm specifically looking at overriding
noscript.ABE.enabled as a test.  The only way I've gotten this to work
is to drop extension-overrides.js into
=~/.tor-browser/foo.default/preferences= (we don't have any special
profile.ini magic in place to keep foo from happening... another thing
we might address).  Note that I have managed to get other preference
mods to take hold by dropping stuff in various places under the
installation dir (=/usr/local/lib/...=), but there are some prefs (like
noscript.ABE.enabled) that I have not been able to frob this
way... all of this requires a lot of investigation and screwing around
with e.g. ktrace.

The thing is, there's more along these lines.  What I've really been
doing here is looking closely at the scripts that are embedded in the
those yml files and trying to understand how we address all of that in
an OpenBSD context.  Even if I do figure out the magic formula for
dealing with preference mods completely there is at least one other
issue to deal with when it comes to PT and that's tor.rc.  In our case
right now we expect it in =~/.tor-browser/tor.rc= (can be missing as per
our tweak to tor-launcher).  When we add PT into the mix, though, we
need customizations there to hook in the various PT modules that ship
with TBB.  This means writing stuff to that tor.rc or installing one
somehow.

All of this is driving me in the same direction: we need a script that
is run, either every time to start up tor-browser or just the first
time to set up your =~/.tor-browser=.  We could hack on run-mozilla.sh
that comes with Firefox if we go the latter way, and I'm beginning to
think that we should.

I don't want to use this as an excuse to sleaze out and go all
"bundle": install random go programs and python cruft under
=~/.tor-browser=, etc.  I still think that every independent piece of
software that is installed in TBB should be turned into a port and the
dependency graph between those ports should be set up so that when you
install TBB (whatever port that ends up being, maybe just tor-browser)
you get all of the packages that it depends on installed.  It's just
the final per-user configuration bits that we need some help with,
since installing a package will not do anything to e.g. your
=~/.tor-browser/tor.rc= file.

So I guess the strategy must be to add a start-tor-browser script to
the port and have it grovel over your =~/.tor-browser= directory the
first time it is run.  At minimum it munges your =~/.tor-browser/tor.rc=
file to hook in all of the PT stuff; if I don't find a more suitable
way to deal with extension-overrides.js and bridge_prefs.js then it
will have to do something about those as well.  It could also deal
with =~/.tor-browser/profiles.ini= to get rid of the foo (random prefix)
problem so we have a known location for things.

If this is the way forward then the plan is:
1. Finish beating the list of necessary ports out of various sh scripts;
   I've started doing this in the Issues section of the openbsd-ports
   repository in the torbsd GH account;
2. Write those ports;
3. Write a start-tor-browser script that deals with tor.rc and whatever
   else that's left; stick it in the tor-browser port, I guess.

As an alternative to start-tor-browser we could have a
setup-tor-browser script and a pkg/MESSAGE that tells the user to run
setup-tor-browser first.  I'm not sure which is better or would find a
better reception among the OpenBSD community, but start-tor-browser
seems less error-prone to me.

...

Okay, scratch all that.  After writing it I had an epiphany: my
concerns are all stupid.  All I have to do is create a ort, say,
tbb-pt, which (a) depends on the individual PT pots I come up with and
(b) contains a complete tor.rc file with all of the stuff we want in
it that gets installed in some sane place.  We can then point at that
file for torrc-defaults in tor-launcher and we don't need to do any
tomfoolery with =~/.tor-browser/tor.rc= or anything else.

So all that's left is figuring out the extension-overrides.js issue,
which I'm sure I can.  Then we don't need no stinking sneaky script.

** 2015-04-07
Had a couple of days of screwing around in meat.space, am back inside
the computer now, where it's safe.

After some feedback from Jiri B. <jiri@devio.us> I'm rearranging the
structure of the ports tree to be saner.  We're ditching the tbb-addon
port module and instead moving that stuff in to www/tbb/Makefile.inc,
where the other addons will use it; I'll harmonize it with
tor-browser's Makefile and then the situation will be more like
e.g. baresip: a set of things that go together.  Nothing outside of
the tor browser bundle wants anything under www/tbb.  The
www/tbb/Makefile then will use bsd.port.subdir.mk and then to build
the whole tbb you do
  # cd /usr/ports/www/tbb; make install

That makes much more sense.
