# $OpenBSD$

MOZILLA_ADDON_NAME =	noscript
V =			2.6.9.19
COMMENT =		Flexible JS Blocker for Firefox (Tor Browser variant)
MOZILLA_ADDON_XPI =	Yes
MAINTAINER =		sean levy <attila@stalphonsos.com>
HOMEPAGE =		http://noscript.net
MASTER_SITES =		https://secure.informaction.com/download/releases/
MODULES =		www/tbb-addon
# GPLv2+
PERMIT_PACKAGE_CDROM =	Yes
GUID =			{73a6fe31-595d-460b-a920-fcc0f8843232}

.include <bsd.port.mk>
