# $OpenBSD$

ADDON_NAME =		noscript
V =			2.9.0.11
COMMENT =		flexible JS blocker for firefox (Tor browser variant)
HOMEPAGE =		http://noscript.net
MASTER_SITES =		https://secure.informaction.com/download/releases/
FETCH_CMD ?= 		/usr/bin/ftp -V ${_PROGRESS} -k ${FTP_KEEPALIVE} -C -S dont
GUID =			{73a6fe31-595d-460b-a920-fcc0f8843232}
DISTFILE_IS_XPI =	Yes

.include <bsd.port.mk>
