# $OpenBSD$

ADDON_NAME =		noscript
V =			2.9.0.2
COMMENT =		flexible JS blocker for firefox (Tor browser variant)
HOMEPAGE =		http://noscript.net
MASTER_SITES =		https://secure.informaction.com/download/releases/
GUID =			{73a6fe31-595d-460b-a920-fcc0f8843232}
ADDON_IS_XPI =		Yes

.include <bsd.port.mk>
