# $OpenBSD$

    SUBDIR =
.if !defined(ADDONS_ONLY)
    SUBDIR += tor-browser
.endif
    SUBDIR += torbutton
    SUBDIR += tor-launcher
    SUBDIR += noscript
    SUBDIR += https-everywhere

.include <bsd.port.subdir.mk>
