# $OpenBSD$

COMMENT=	Tor Browser meta-package

MAINTAINER=	Sean Levy <attila@stalphonsos.com>

PKGNAME=	tor-browser-6.0.5

RUN_DEPENDS=	www/tor-browser/tb-browser \
		www/tor-browser/tb-torbutton \
		www/tor-browser/tb-tor-launcher \
		www/tor-browser/tb-noscript \
		www/tor-browser/tb-https-everywhere

.include <bsd.port.mk>
