# $OpenBSD$

COMMENT=	Tor Browser meta package

MAINTAINER=	Sean Levy <attila@stalphonsos.com>

PKGNAME=	tor-browser-6.0.5

RUN_DEPENDS=	www/tor-browser/browser \
		www/tor-browser/torbutton \
		www/tor-browser/tor-launcher \
		www/tor-browser/noscript \
		www/tor-browser/https-everywhere

.include <bsd.port.mk>
