# $OpenBSD: Makefile.template,v 1.76 2017/02/25 16:04:20 danj Exp $

COMMENT =		declarative layer for SQLAlchemey

MODPY_EGG_VERSION =	0.7.1
DISTNAME =		Elixir-${MODPY_EGG_VERSION}
PKGNAME =		py-elixir-${MODPY_EGG_VERSION}

CATEGORIES =		databases

MAINTAINER =		George Rosamond <george@nycbug.org>

# MIT
PERMIT_PACKAGE_CDROM =	Yes

MODULES =		lang/python

MODPY_SETUPTOOLS =	Yes

FLAVORS =		python2
FLAVOR ?=

.include <bsd.port.mk>
